import type { Product } from '@/types';

/**
 * Expanded product catalog using all available brand images
 * Each image from the brand folders is assigned to a product
 */

// KOLORS Products (21 images)
const kolorsProducts: Product[] = Array.from({ length: 21 }, (_, i) => ({
  id: `kolors-${100 + i}`,
  name: `Kolors ${['Modular Switch', 'Socket', '2-Way Switch', '3-Pin Socket', 'Bell Push', 'Fan Regulator', 'Dimmer Switch', 'USB Charger', 'Data Socket', 'TV Socket'][i % 10]} ${Math.floor(i / 10) + 1}`,
  slug: `kolors-product-${100 + i}`,
  description: `Premium Kolors electrical product - high quality and durable`,
  long_description: `Authentic Kolors electrical product. Premium quality with modern design and reliable performance.`,
  price: 2.50 + (i * 0.30),
  category: 'Switches & Sockets',
  brand: 'Kolors',
  image_url: '',
  stock: 50 + (i * 10),
  specifications: { 'Brand': 'Kolors', 'Rating': '16A', 'Type': 'Modular' },
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
}));

// LEGRAND Products (17 images)
const legrandProducts: Product[] = Array.from({ length: 17 }, (_, i) => ({
  id: `legrand-${200 + i}`,
  name: `Legrand ${['Mylinc Switch', 'Arteor Socket', 'Belanko Switch', 'Galion Socket', 'Mallia Switch', 'Lyncus Socket', 'Valena Switch'][i % 7]} ${Math.floor(i / 7) + 1}`,
  slug: `legrand-product-${200 + i}`,
  description: `Premium Legrand electrical accessories - French engineering excellence`,
  long_description: `Authentic Legrand product. World-class quality with innovative design and superior safety features.`,
  price: 4.00 + (i * 0.50),
  category: 'Switches & Sockets',
  brand: 'Legrand',
  image_url: '',
  stock: 40 + (i * 8),
  specifications: { 'Brand': 'Legrand', 'Rating': '16A', 'Type': 'Modular', 'Series': 'Premium' },
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
}));

// NORISYS Products (19 images)
const norisysProducts: Product[] = Array.from({ length: 19 }, (_, i) => ({
  id: `norisys-${300 + i}`,
  name: `Norisys ${['Cube Switch', 'Veto Socket', 'Classico Switch', 'Verve Socket', 'Jazz Switch', 'Step Socket', 'Bell Push'][i % 7]} ${Math.floor(i / 7) + 1}`,
  slug: `norisys-product-${300 + i}`,
  description: `Elegant Norisys electrical products - style meets functionality`,
  long_description: `Authentic Norisys product. Elegant design with premium finish and reliable performance.`,
  price: 3.50 + (i * 0.40),
  category: 'Switches & Sockets',
  brand: 'Norisys',
  image_url: '',
  stock: 45 + (i * 9),
  specifications: { 'Brand': 'Norisys', 'Rating': '16A', 'Type': 'Modular' },
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
}));

// PANASONIC Products (7 images)
const panasonicProducts: Product[] = Array.from({ length: 7 }, (_, i) => ({
  id: `panasonic-${400 + i}`,
  name: `Panasonic ${['Roma Switch', 'Friz Switch', 'Refina Socket', 'Thea Switch', 'Modular Socket', 'Bell Push', 'Fan Regulator'][i]}`,
  slug: `panasonic-product-${400 + i}`,
  description: `Trusted Panasonic electrical products - Japanese quality and reliability`,
  long_description: `Authentic Panasonic product. Japanese engineering with unmatched reliability and safety standards.`,
  price: 3.80 + (i * 0.60),
  category: 'Switches & Sockets',
  brand: 'Panasonic',
  image_url: '',
  stock: 60 + (i * 12),
  specifications: { 'Brand': 'Panasonic', 'Rating': '16A', 'Type': 'Modular', 'Origin': 'Japan Tech' },
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
}));

// FINOLEX Products (9 images: 4 switches + 5 cables)
const finolexProducts: Product[] = [
  // Switches (4 images)
  ...Array.from({ length: 4 }, (_, i) => ({
    id: `finolex-${500 + i}`,
    name: `Finolex ${['16A Modular Switch', '10A 2-Way Switch', '6A Bell Push', '16A 3-Pin Socket'][i]}`,
    slug: `finolex-switch-${500 + i}`,
    description: `Premium Finolex modular switches - trusted Indian brand`,
    long_description: `Authentic Finolex electrical switch. Made in India with premium materials and superior safety features.`,
    price: 2.80 + (i * 0.40),
    category: 'Switches & Sockets',
    brand: 'Finolex',
    image_url: '',
    stock: 100 + (i * 15),
    specifications: { 'Brand': 'Finolex', 'Rating': '16A', 'Type': 'Modular', 'Made in': 'India' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  })),
  // Cables (5 images)
  ...Array.from({ length: 5 }, (_, i) => ({
    id: `finolex-${510 + i}`,
    name: `Finolex ${['2.5mm² FR Wire', '1.5mm² House Wire', '4mm² Submersible Cable', '6mm² Power Cable', '1mm² Flexible Wire'][i]}`,
    slug: `finolex-cable-${510 + i}`,
    description: `High quality Finolex cables and wires - flame retardant and durable`,
    long_description: `Authentic Finolex cable. ISI certified with superior insulation and long-lasting performance.`,
    price: 15.00 + (i * 8.00),
    category: 'Cables & Wires',
    brand: 'Finolex',
    image_url: '',
    stock: 80 + (i * 20),
    specifications: { 'Brand': 'Finolex', 'Type': 'FR Cable', 'Length': '90m', 'ISI': 'Certified' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  })),
];

// ANCHOR Products (15 images: 7 switches/plates + 8 wires/cables)
const anchorProducts: Product[] = [
  // Switches and Plates (7 images)
  {
    id: 'anchor-600',
    name: 'Anchor Roma Modular Switch 10A 1-Way',
    slug: 'anchor-roma-modular-switch-10a-1-way',
    description: 'Iconic Roma modular switch engineered for long-lasting reliability',
    long_description: 'Authentic Anchor Roma modular switch. Features smooth rocking action, silver alloy contacts, and ISI certified electrical safety standards.',
    price: 2.20,
    category: 'Switches & Sockets',
    brand: 'Anchor',
    image_url: '/images/anchor/switch (1).jpeg',
    stock: 150,
    specifications: { 'Brand': 'Anchor', 'Series': 'Roma', 'Rating': '10A 240V', 'Type': 'Modular Switch' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'anchor-601',
    name: 'Anchor Penta 6A Piano Switch',
    slug: 'anchor-penta-6a-piano-switch-authentic',
    description: 'Traditional heavy-duty piano switch by Anchor',
    long_description: 'Authentic Anchor Penta non-modular piano switch. Built with robust urea-formaldehyde housing and tested for over 100,000 operations.',
    price: 1.50,
    category: 'Switches & Sockets',
    brand: 'Anchor',
    image_url: '/images/anchor/switch (1).jpg',
    stock: 250,
    specifications: { 'Brand': 'Anchor', 'Series': 'Penta', 'Rating': '6A 240V', 'Type': 'Piano Switch' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'anchor-602',
    name: 'Anchor Roma Classic 16A Power Switch',
    slug: 'anchor-roma-classic-16a-power-switch',
    description: 'High current 16A modular switch with neon indicator',
    long_description: 'Heavy duty 16A switch for appliances like geysers, air conditioners, and kitchen equipment. High spark suppression mechanism.',
    price: 3.40,
    category: 'Switches & Sockets',
    brand: 'Anchor',
    image_url: '/images/anchor/switch (1).png',
    stock: 120,
    specifications: { 'Brand': 'Anchor', 'Series': 'Roma Classic', 'Rating': '16A Heavy Duty', 'Type': 'Power Switch' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'anchor-603',
    name: 'Anchor Vision Flat Modular Switch',
    slug: 'anchor-vision-flat-modular-switch',
    description: 'Sleek flush-finish minimalist switch module',
    long_description: 'Modern flat-design modular switch from the Anchor Vision series. Ultra-low profile with soft-click actuation.',
    price: 3.80,
    category: 'Switches & Sockets',
    brand: 'Anchor',
    image_url: '/images/anchor/switch (1).webp',
    stock: 90,
    specifications: { 'Brand': 'Anchor', 'Series': 'Vision', 'Rating': '10A', 'Type': 'Flat Modular Switch' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'anchor-604',
    name: 'Anchor Rider 16A 3-Pin Universal Socket',
    slug: 'anchor-rider-16a-3-pin-universal-socket',
    description: '16A/6A twin shutter socket with safety protection',
    long_description: 'Multi-pin universal socket with integrated child safety shutters and phosphor bronze contacts for firm grip.',
    price: 3.90,
    category: 'Switches & Sockets',
    brand: 'Anchor',
    image_url: '/images/anchor/switch (2).jpg',
    stock: 110,
    specifications: { 'Brand': 'Anchor', 'Series': 'Rider', 'Rating': '16A / 6A Dual', 'Type': 'Socket' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'anchor-605',
    name: 'Anchor Woods 2-Way Bell Push Module',
    slug: 'anchor-woods-2-way-bell-push-module',
    description: 'Premium bell push switch with nameplate slot',
    long_description: 'Durable spring-loaded bell push switch module designed for commercial and residential door entrances.',
    price: 2.90,
    category: 'Switches & Sockets',
    brand: 'Anchor',
    image_url: '/images/anchor/switch (3).jpg',
    stock: 80,
    specifications: { 'Brand': 'Anchor', 'Series': 'Woods', 'Rating': '6A', 'Type': 'Bell Push' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'anchor-606',
    name: 'Anchor Modular Colour Cover Plate',
    slug: 'anchor-modular-colour-cover-plate',
    description: 'Designer accent finish modular front plate',
    long_description: 'Scratch resistant, UV stabilized modular plate that blends seamlessly with modern wall finishes and textures.',
    price: 4.50,
    category: 'Switches & Sockets',
    brand: 'Anchor',
    image_url: '/images/anchor/colour-plate.png',
    stock: 140,
    specifications: { 'Brand': 'Anchor', 'Material': 'Polycarbonate', 'Type': 'Front Cover Plate' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  // Wires and Cables (8 images)
  {
    id: 'anchor-607',
    name: 'Anchor Advance 1.0 sqmm FR Wire (90m)',
    slug: 'anchor-advance-1-0-sqmm-fr-wire-90m',
    description: 'Flame retardant 1.0 sqmm electrical wire coil',
    long_description: '100% electrolytic grade copper with 99.97% purity. 90m coil with superior fire retardant PVC insulation.',
    price: 18.00,
    category: 'Cables & Wires',
    brand: 'Anchor',
    image_url: '/images/anchor/wire (1).jpeg',
    stock: 95,
    specifications: { 'Brand': 'Anchor', 'Gauge': '1.0 sqmm', 'Length': '90m Coil', 'Type': 'FR Copper Wire' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'anchor-608',
    name: 'Anchor Advance Plus 1.5 sqmm House Wire',
    slug: 'anchor-advance-plus-1-5-sqmm-house-wire',
    description: '1.5 sqmm single core multi-strand building wire',
    long_description: 'Engineered for lighting and medium power load circuits. High oxygen index prevents spread of fire.',
    price: 24.50,
    category: 'Cables & Wires',
    brand: 'Anchor',
    image_url: '/images/anchor/wire (1).jpg',
    stock: 120,
    specifications: { 'Brand': 'Anchor', 'Gauge': '1.5 sqmm', 'Length': '90m Coil', 'Type': 'House Wire' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'anchor-609',
    name: 'Anchor Ziva 2.5 sqmm Flame Retardant Wire',
    slug: 'anchor-ziva-2-5-sqmm-flame-retardant-wire',
    description: '2.5 sqmm power wire for sockets and air conditioners',
    long_description: 'Premium multi-strand copper wire rated for up to 22A continuous current. Heat resistant up to 85°C.',
    price: 36.00,
    category: 'Cables & Wires',
    brand: 'Anchor',
    image_url: '/images/anchor/wire (1).png',
    stock: 85,
    specifications: { 'Brand': 'Anchor', 'Gauge': '2.5 sqmm', 'Length': '90m Coil', 'Type': 'FR Wire' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'anchor-610',
    name: 'Anchor Heavy Duty 4.0 sqmm Power Cable',
    slug: 'anchor-heavy-duty-4-0-sqmm-power-cable',
    description: '4.0 sqmm high capacity mains & inverter cable',
    long_description: 'Low electrical resistance for high load appliances such as main panel distribution, geysers, and EV chargers.',
    price: 52.00,
    category: 'Cables & Wires',
    brand: 'Anchor',
    image_url: '/images/anchor/wire (2).jpeg',
    stock: 60,
    specifications: { 'Brand': 'Anchor', 'Gauge': '4.0 sqmm', 'Length': '90m Coil', 'Type': 'Heavy Duty Cable' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'anchor-611',
    name: 'Anchor Industrial 6.0 sqmm Heavy Load Cable',
    slug: 'anchor-industrial-6-0-sqmm-heavy-load-cable',
    description: '6.0 sqmm heavy industrial single core cable',
    long_description: 'Designed for sub-main power feeds, heavy motor loads, and industrial grade power boards with zero voltage drop.',
    price: 78.00,
    category: 'Cables & Wires',
    brand: 'Anchor',
    image_url: '/images/anchor/wire (2).jpg',
    stock: 45,
    specifications: { 'Brand': 'Anchor', 'Gauge': '6.0 sqmm', 'Length': '90m Coil', 'Type': 'Industrial Cable' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'anchor-612',
    name: 'Anchor Flexible 3-Core Submersible Cable',
    slug: 'anchor-flexible-3-core-submersible-cable',
    description: 'Waterproof 3-core flat submersible pump cable',
    long_description: 'Special grade PVC sheathed flexible flat cable resistant to water abrasion, moisture, and extreme temperature conditions.',
    price: 65.00,
    category: 'Cables & Wires',
    brand: 'Anchor',
    image_url: '/images/anchor/wire (3).jpg',
    stock: 40,
    specifications: { 'Brand': 'Anchor', 'Type': '3-Core Flat Cable', 'Use': 'Submersible Pumps' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'anchor-613',
    name: 'Anchor Multi-Strand Heat Resistant Wire',
    slug: 'anchor-multi-strand-heat-resistant-wire',
    description: 'High heat resistant flexible wiring coil',
    long_description: 'HR-FRLSH (Heat Resistant Flame Retardant Low Smoke Halogen) copper cable for critical safety installations.',
    price: 42.00,
    category: 'Cables & Wires',
    brand: 'Anchor',
    image_url: '/images/anchor/wire (4).jpg',
    stock: 70,
    specifications: { 'Brand': 'Anchor', 'Grade': 'HR-FRLSH', 'Length': '90m Coil', 'Type': 'Safety Wire' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'anchor-614',
    name: 'Anchor Armoured Mains Power Cable',
    slug: 'anchor-armoured-mains-power-cable',
    description: 'Armoured underground electrical service cable',
    long_description: 'Steel wire armoured cable providing maximum mechanical protection for underground and outdoor distribution networks.',
    price: 95.00,
    category: 'Cables & Wires',
    brand: 'Anchor',
    image_url: '/images/anchor/wire.png',
    stock: 35,
    specifications: { 'Brand': 'Anchor', 'Type': 'Armoured Power Cable', 'Use': 'Main Incoming Line' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// Export all expanded products
export const EXPANDED_PRODUCTS: Product[] = [
  ...anchorProducts,
  ...kolorsProducts,
  ...legrandProducts,
  ...norisysProducts,
  ...panasonicProducts,
  ...finolexProducts,
];

// Export by brand for easy filtering
export const PRODUCTS_BY_BRAND = {
  anchor: anchorProducts,
  kolors: kolorsProducts,
  legrand: legrandProducts,
  norisys: norisysProducts,
  panasonic: panasonicProducts,
  finolex: finolexProducts,
};
