import type { Product } from '@/types';

const ts = new Date().toISOString();

// ─── KOLORS (19 switch images) ────────────────────────────────────────────────
const KOLORS_IMAGES = [
  '/images/kolors/switch.jpg',
  '/images/kolors/switch1.jpeg',
  '/images/kolors/switch2.jpeg',
  '/images/kolors/switch3.jpeg',
  '/images/kolors/switch4.jpeg',
  '/images/kolors/switch6.jpeg',
  '/images/kolors/switch7.jpeg',
  '/images/kolors/switch8.jpeg',
  '/images/kolors/switch9.jpeg',
  '/images/kolors/switch10.jpeg',
  '/images/kolors/switch11.jpeg',
  '/images/kolors/switch12.jpeg',
  '/images/kolors/switch13.jpeg',
  '/images/kolors/switch14.jpeg',
  '/images/kolors/switch15.jpeg',
  '/images/kolors/switch16.jpeg',
  '/images/kolors/switch17.jpeg',
  '/images/kolors/switch18.jpeg',
  '/images/kolors/switch19.jpeg',
];

const KOLORS_NAMES = [
  'Kolors Krest 6A 1-Way Modular Switch',
  'Kolors Silvia 10A 2-Way Switch',
  'Kolors K-Cube 16A Power Socket',
  'Kolors Bell Push Module',
  'Kolors Fan Regulator Electronic',
  'Kolors Dimmer Switch 200W',
  'Kolors USB Type-C Charger Socket',
  'Kolors 16A 3-Pin Socket',
  'Kolors TV/Data Combo Socket',
  'Kolors 6A 2-Way Switch',
  'Kolors Blanking Plate Module',
  'Kolors Master Fan Switch 10A',
  'Kolors 2M Cover Plate',
  'Kolors 3M Modular Frame',
  'Kolors Indicator Switch 6A',
  'Kolors AC Power Socket 16A',
  'Kolors Smart Touch Dimmer',
  'Kolors 10A 1-Way Switch Premium',
  'Kolors Metallic Finish Switch',
];

const kolorsProducts: Product[] = KOLORS_IMAGES.map((img, i) => ({
  id: `kolors-${100 + i}`,
  name: KOLORS_NAMES[i] ?? `Kolors Modular Switch ${i + 1}`,
  slug: `kolors-product-${100 + i}`,
  description: 'Contemporary modular switch for modern interiors',
  long_description: 'Kolors electrical fitting with premium polycarbonate housing, silver alloy contacts, and ISI marked performance.',
  price: parseFloat((2.50 + i * 0.28).toFixed(2)),
  category: 'Switches & Sockets',
  brand: 'Kolors',
  image_url: img,
  stock: 50 + i * 9,
  specifications: { Brand: 'Kolors', Rating: i % 3 === 0 ? '16A' : '10A', Type: 'Modular', Series: 'Krest' },
  created_at: ts,
  updated_at: ts,
}));

// ─── LEGRAND (17 switch images) ───────────────────────────────────────────────
const LEGRAND_IMAGES = [
  '/images/legrand/switch.jpeg',
  '/images/legrand/switch1.jpeg',
  '/images/legrand/switch2.jpeg',
  '/images/legrand/switch3.jpeg',
  '/images/legrand/switch4.jpeg',
  '/images/legrand/switch5.jpeg',
  '/images/legrand/switch6.jpeg',
  '/images/legrand/switch7.jpeg',
  '/images/legrand/switch8.jpeg',
  '/images/legrand/switch9.jpeg',
  '/images/legrand/switch10.jpeg',
  '/images/legrand/switch11.jpeg',
  '/images/legrand/switch12.jpeg',
  '/images/legrand/switch13.jpeg',
  '/images/legrand/switch14.jpeg',
  '/images/legrand/switch15.jpeg',
  '/images/legrand/switch16.jpg',
];

const LEGRAND_NAMES = [
  'Legrand Mylinc 6A 1-Way Switch',
  'Legrand Mylinc 10A 2-Way Switch',
  'Legrand Arteor 16A Power Socket',
  'Legrand Belanko 6A Bell Push',
  'Legrand Mallia Fan Regulator',
  'Legrand Galion 16A 3-Pin Socket',
  'Legrand Lyncus Dimmer 300W',
  'Legrand Valena USB Charger',
  'Legrand Mylinc 20A Switch',
  'Legrand Arteor TV/SAT Socket',
  'Legrand Belanko 2-Way Switch',
  'Legrand Mylinc Blank Plate',
  'Legrand Arteor HDMI Socket',
  'Legrand Mylinc 3M Frame',
  'Legrand Galion Indicator Switch',
  'Legrand Arteor Series Plate',
  'Legrand Valena Next Switch',
];

const legrandProducts: Product[] = LEGRAND_IMAGES.map((img, i) => ({
  id: `legrand-${200 + i}`,
  name: LEGRAND_NAMES[i] ?? `Legrand Modular Switch ${i + 1}`,
  slug: `legrand-product-${200 + i}`,
  description: 'French engineered modular electrical accessories',
  long_description: 'Legrand product combining European ergonomics with durable polycarbonate and arc-resistant silver-nickel contacts.',
  price: parseFloat((4.00 + i * 0.48).toFixed(2)),
  category: 'Switches & Sockets',
  brand: 'Legrand',
  image_url: img,
  stock: 40 + i * 8,
  specifications: { Brand: 'Legrand', Rating: i % 4 === 0 ? '16A' : '10A', Type: 'Modular', Series: 'Mylinc' },
  created_at: ts,
  updated_at: ts,
}));

// ─── NORISYS (19 switch images) ───────────────────────────────────────────────
const NORISYS_IMAGES = [
  '/images/norisys/switch (1).jpeg',
  '/images/norisys/switch (2).jpeg',
  '/images/norisys/switch (3).jpeg',
  '/images/norisys/switch (4).jpeg',
  '/images/norisys/switch (5).jpeg',
  '/images/norisys/switch (6).jpeg',
  '/images/norisys/switch (7).jpeg',
  '/images/norisys/switch (8).jpeg',
  '/images/norisys/switch (9).jpeg',
  '/images/norisys/switch (10).jpeg',
  '/images/norisys/switch (11).jpeg',
  '/images/norisys/switch (12).jpeg',
  '/images/norisys/switch (13).jpeg',
  '/images/norisys/switch (14).jpeg',
  '/images/norisys/switch (15).jpeg',
  '/images/norisys/switch (16).jpeg',
  '/images/norisys/switch (17).jpeg',
  '/images/norisys/switch (18).jpeg',
  '/images/norisys/switch (19).jpeg',
];

const NORISYS_NAMES = [
  'Norisys Cube 6A 1-Way Switch',
  'Norisys Cube 10A 2-Way Switch',
  'Norisys Veto 16A Power Socket',
  'Norisys Classico Bell Push',
  'Norisys Verve Fan Regulator',
  'Norisys Jazz 16A 3-Pin Socket',
  'Norisys Step Dimmer 200W',
  'Norisys Cube USB Socket',
  'Norisys Veto 25A Heavy Switch',
  'Norisys Classico TV Socket',
  'Norisys Cube 2-Way Indicator',
  'Norisys Verve Blank Module',
  'Norisys Jazz 3M Frame',
  'Norisys Cube Combo Plate',
  'Norisys Step Series Switch',
  'Norisys Classico 10A Switch',
  'Norisys Veto Series Plate',
  'Norisys Jazz Bell Push',
  'Norisys Cube Premium 16A',
];

const norisysProducts: Product[] = NORISYS_IMAGES.map((img, i) => ({
  id: `norisys-${300 + i}`,
  name: NORISYS_NAMES[i] ?? `Norisys Cube Switch ${i + 1}`,
  slug: `norisys-product-${300 + i}`,
  description: 'Minimalist European design with heavy load capacity',
  long_description: 'Norisys switch with solid aluminum accent trim, crisp actuation, and high endurance 10,000-cycle contact metallurgy.',
  price: parseFloat((3.50 + i * 0.38).toFixed(2)),
  category: 'Switches & Sockets',
  brand: 'Norisys',
  image_url: img,
  stock: 45 + i * 9,
  specifications: { Brand: 'Norisys', Rating: i % 3 === 0 ? '16A' : '10A', Type: 'Modular', Series: 'Cube' },
  created_at: ts,
  updated_at: ts,
}));

// ─── PANASONIC (7 switch images) ──────────────────────────────────────────────
const PANASONIC_IMAGES = [
  '/images/panasonic/switch (1).jpeg',
  '/images/panasonic/switch (1).jpg',
  '/images/panasonic/switch (1).png',
  '/images/panasonic/switch (1).webp',
  '/images/panasonic/switch (2).jpeg',
  '/images/panasonic/switch (2).png',
  '/images/panasonic/switch (3).png',
];

const PANASONIC_NAMES = [
  'Panasonic Roma 6A 1-Way Switch',
  'Panasonic Friz 10A 2-Way Switch',
  'Panasonic Refina 16A Socket',
  'Panasonic Thea Fan Regulator',
  'Panasonic Roma 16A 3-Pin Socket',
  'Panasonic Vision Bell Push',
  'Panasonic Roma Plus 2-Way Switch',
];

const panasonicProducts: Product[] = PANASONIC_IMAGES.map((img, i) => ({
  id: `panasonic-${400 + i}`,
  name: PANASONIC_NAMES[i],
  slug: `panasonic-product-${400 + i}`,
  description: 'Japanese precision engineering for modern homes',
  long_description: 'Panasonic electrical accessory manufactured to stringent international safety standards with superior arc resistance and soft-click action.',
  price: parseFloat((3.80 + i * 0.55).toFixed(2)),
  category: 'Switches & Sockets',
  brand: 'Panasonic',
  image_url: img,
  stock: 60 + i * 12,
  specifications: { Brand: 'Panasonic', Rating: '10A', Type: 'Modular', Origin: 'Japan Tech' },
  created_at: ts,
  updated_at: ts,
}));

// ─── FINOLEX (4 switches + 5 cables) ─────────────────────────────────────────
const finolexProducts: Product[] = [
  {
    id: 'finolex-500',
    name: 'Finolex Flatguard 16A Modular Switch',
    slug: 'finolex-switch-500',
    description: 'Flame retardant 16A modular switch, ISI certified',
    long_description: 'Finolex Flatguard modular switch with high-impact polycarbonate housing, silver alloy contacts, and fire-retardant insulation.',
    price: 2.80,
    category: 'Switches & Sockets',
    brand: 'Finolex',
    image_url: '/images/finolex/switch (1).jpg',
    stock: 130,
    specifications: { Brand: 'Finolex', Rating: '16A', Type: 'Modular', Certification: 'ISI' },
    created_at: ts,
    updated_at: ts,
  },
  {
    id: 'finolex-501',
    name: 'Finolex Flatguard 10A 2-Way Switch',
    slug: 'finolex-switch-501',
    description: '10A 2-way modular switch for staircase wiring',
    long_description: 'Purpose-built staircase switch with reliable two-way operation and corrosion-resistant contacts.',
    price: 3.20,
    category: 'Switches & Sockets',
    brand: 'Finolex',
    image_url: '/images/finolex/switch (2).jpg',
    stock: 115,
    specifications: { Brand: 'Finolex', Rating: '10A', Type: '2-Way Switch', Certification: 'ISI' },
    created_at: ts,
    updated_at: ts,
  },
  {
    id: 'finolex-502',
    name: 'Finolex 6A Bell Push Module',
    slug: 'finolex-switch-502',
    description: 'Spring-loaded bell push switch module',
    long_description: 'Durable spring-return bell push for door entry systems. Compatible with all standard modular frames.',
    price: 2.40,
    category: 'Switches & Sockets',
    brand: 'Finolex',
    image_url: '/images/finolex/switch (3).jpg',
    stock: 200,
    specifications: { Brand: 'Finolex', Rating: '6A', Type: 'Bell Push' },
    created_at: ts,
    updated_at: ts,
  },
  {
    id: 'finolex-503',
    name: 'Finolex 16A 3-Pin Universal Socket',
    slug: 'finolex-switch-503',
    description: '16A heavy-duty socket with child safety shutters',
    long_description: 'Finolex heavy-duty 16A socket with automatic child safety shutters, phosphor bronze contacts, and high-impact polycarbonate housing.',
    price: 3.60,
    category: 'Switches & Sockets',
    brand: 'Finolex',
    image_url: '/images/finolex/switch (4).jpg',
    stock: 95,
    specifications: { Brand: 'Finolex', Rating: '16A', Type: 'Universal Socket', Certification: 'ISI' },
    created_at: ts,
    updated_at: ts,
  },
  {
    id: 'finolex-510',
    name: 'Finolex Flame-Gard 1.5 sqmm FR Wire (90m)',
    slug: 'finolex-cable-510',
    description: '1.5 sqmm flame retardant copper house wire',
    long_description: 'Finolex 99.97% pure electrolytic copper conductor with high oxygen index PVC insulation. ISI certified, rated 1100V.',
    price: 22.00,
    category: 'Cables & Wires',
    brand: 'Finolex',
    image_url: '/images/finolex/cable (1).jpg',
    stock: 90,
    specifications: { Brand: 'Finolex', Gauge: '1.5 sqmm', Length: '90m', Type: 'FR Wire', Certification: 'ISI' },
    created_at: ts,
    updated_at: ts,
  },
  {
    id: 'finolex-511',
    name: 'Finolex Flame-Gard 2.5 sqmm FR Wire (90m)',
    slug: 'finolex-cable-511',
    description: '2.5 sqmm power wire for sockets and AC circuits',
    long_description: 'Multi-strand copper wire rated 22A continuous. Heat resistant to 85°C with low smoke halogen-free insulation option.',
    price: 34.00,
    category: 'Cables & Wires',
    brand: 'Finolex',
    image_url: '/images/finolex/cable (2).jpg',
    stock: 75,
    specifications: { Brand: 'Finolex', Gauge: '2.5 sqmm', Length: '90m', Type: 'FR Wire', Certification: 'ISI' },
    created_at: ts,
    updated_at: ts,
  },
  {
    id: 'finolex-512',
    name: 'Finolex 4.0 sqmm Power Cable (90m)',
    slug: 'finolex-cable-512',
    description: '4.0 sqmm high capacity mains and inverter cable',
    long_description: 'High conductivity low resistance cable for DB mains, heavy appliances, and inverter connections.',
    price: 52.00,
    category: 'Cables & Wires',
    brand: 'Finolex',
    image_url: '/images/finolex/cable (3).jpg',
    stock: 60,
    specifications: { Brand: 'Finolex', Gauge: '4.0 sqmm', Length: '90m', Type: 'Power Cable' },
    created_at: ts,
    updated_at: ts,
  },
  {
    id: 'finolex-513',
    name: 'Finolex 6.0 sqmm Heavy Duty Cable (90m)',
    slug: 'finolex-cable-513',
    description: '6.0 sqmm sub-main cable for heavy loads',
    long_description: 'Designed for sub-main distribution, heavy motor circuits, and high-current industrial panel feeds.',
    price: 76.00,
    category: 'Cables & Wires',
    brand: 'Finolex',
    image_url: '/images/finolex/cable (4).jpg',
    stock: 45,
    specifications: { Brand: 'Finolex', Gauge: '6.0 sqmm', Length: '90m', Type: 'Heavy Duty Cable' },
    created_at: ts,
    updated_at: ts,
  },
  {
    id: 'finolex-514',
    name: 'Finolex 1.0 sqmm Submersible Cable',
    slug: 'finolex-cable-514',
    description: '1.0 sqmm waterproof submersible pump cable',
    long_description: 'Special grade PVC compound for continuous water immersion. Abrasion and moisture resistant for borewell pump applications.',
    price: 16.00,
    category: 'Cables & Wires',
    brand: 'Finolex',
    image_url: '/images/finolex/cable (5).jpg',
    stock: 80,
    specifications: { Brand: 'Finolex', Gauge: '1.0 sqmm', Type: 'Submersible Cable', Use: 'Pump Wiring' },
    created_at: ts,
    updated_at: ts,
  },
];

// ─── ANCHOR (explicit per-product image mapping) ──────────────────────────────
const anchorProducts: Product[] = [
  {
    id: 'anchor-600',
    name: 'Anchor Roma 10A 1-Way Modular Switch',
    slug: 'anchor-roma-10a-1-way-modular-switch',
    description: 'Iconic Roma modular switch engineered for long life',
    long_description: 'Anchor Roma modular switch with silver alloy contacts, smooth rocking action, and ISI certified safety. Rated for 100,000 operations.',
    price: 2.20,
    category: 'Switches & Sockets',
    brand: 'Anchor',
    image_url: '/images/anchor/switch (1).jpeg',
    stock: 150,
    specifications: { Brand: 'Anchor', Series: 'Roma', Rating: '10A 240V', Type: 'Modular Switch' },
    created_at: ts,
    updated_at: ts,
  },
  {
    id: 'anchor-601',
    name: 'Anchor Penta 6A Piano Switch',
    slug: 'anchor-penta-6a-piano-switch',
    description: 'Heavy-duty traditional piano switch by Anchor',
    long_description: 'Anchor Penta non-modular piano switch. Urea-formaldehyde housing, tested for over 100,000 operations, ISI marked.',
    price: 1.50,
    category: 'Switches & Sockets',
    brand: 'Anchor',
    image_url: '/images/anchor/switch (1).jpg',
    stock: 250,
    specifications: { Brand: 'Anchor', Series: 'Penta', Rating: '6A 240V', Type: 'Piano Switch' },
    created_at: ts,
    updated_at: ts,
  },
  {
    id: 'anchor-602',
    name: 'Anchor Roma Classic 16A Power Switch',
    slug: 'anchor-roma-classic-16a-power-switch',
    description: '16A modular switch for geysers and AC units',
    long_description: 'High current 16A switch with spark suppression mechanism. Suitable for geysers, ACs, and high wattage appliances.',
    price: 3.40,
    category: 'Switches & Sockets',
    brand: 'Anchor',
    image_url: '/images/anchor/switch (1).png',
    stock: 120,
    specifications: { Brand: 'Anchor', Series: 'Roma Classic', Rating: '16A Heavy Duty', Type: 'Power Switch' },
    created_at: ts,
    updated_at: ts,
  },
  {
    id: 'anchor-603',
    name: 'Anchor Vision Flat Modular Switch',
    slug: 'anchor-vision-flat-modular-switch',
    description: 'Sleek flush-finish minimalist switch module',
    long_description: 'Anchor Vision flat modular switch with ultra-low profile, soft-click actuation, and UV-stabilised housing.',
    price: 3.80,
    category: 'Switches & Sockets',
    brand: 'Anchor',
    image_url: '/images/anchor/switch (1).webp',
    stock: 90,
    specifications: { Brand: 'Anchor', Series: 'Vision', Rating: '10A', Type: 'Flat Modular Switch' },
    created_at: ts,
    updated_at: ts,
  },
  {
    id: 'anchor-604',
    name: 'Anchor Rider 16A Universal Socket',
    slug: 'anchor-rider-16a-universal-socket',
    description: '16A/6A twin shutter socket with safety shutters',
    long_description: 'Multi-pin universal socket with integrated child safety shutters and phosphor bronze contacts for firm plug grip.',
    price: 3.90,
    category: 'Switches & Sockets',
    brand: 'Anchor',
    image_url: '/images/anchor/switch (2).jpg',
    stock: 110,
    specifications: { Brand: 'Anchor', Series: 'Rider', Rating: '16A / 6A Dual', Type: 'Socket' },
    created_at: ts,
    updated_at: ts,
  },
  {
    id: 'anchor-605',
    name: 'Anchor Woods 6A Bell Push Module',
    slug: 'anchor-woods-6a-bell-push-module',
    description: 'Spring-loaded bell push switch with nameplate slot',
    long_description: 'Durable spring-loaded bell push module for residential and commercial door entrances. Snap-fit modular frame compatible.',
    price: 2.90,
    category: 'Switches & Sockets',
    brand: 'Anchor',
    image_url: '/images/anchor/switch (3).jpg',
    stock: 80,
    specifications: { Brand: 'Anchor', Series: 'Woods', Rating: '6A', Type: 'Bell Push' },
    created_at: ts,
    updated_at: ts,
  },
  {
    id: 'anchor-606',
    name: 'Anchor Modular Colour Cover Plate',
    slug: 'anchor-modular-colour-cover-plate',
    description: 'Designer accent finish modular front plate',
    long_description: 'Scratch-resistant, UV-stabilised modular plate. Blends with modern wall finishes and available in multiple shades.',
    price: 4.50,
    category: 'Switches & Sockets',
    brand: 'Anchor',
    image_url: '/images/anchor/colour-plate.png',
    stock: 140,
    specifications: { Brand: 'Anchor', Material: 'Polycarbonate', Type: 'Cover Plate' },
    created_at: ts,
    updated_at: ts,
  },
  {
    id: 'anchor-607',
    name: 'Anchor Advance 1.0 sqmm FR Wire (90m)',
    slug: 'anchor-advance-1-0-sqmm-fr-wire-90m',
    description: 'Flame retardant 1.0 sqmm electrical wire coil',
    long_description: '100% electrolytic grade copper, 99.97% purity. 90m coil with superior fire retardant PVC insulation.',
    price: 18.00,
    category: 'Cables & Wires',
    brand: 'Anchor',
    image_url: '/images/anchor/wire (1).jpeg',
    stock: 95,
    specifications: { Brand: 'Anchor', Gauge: '1.0 sqmm', Length: '90m', Type: 'FR Copper Wire' },
    created_at: ts,
    updated_at: ts,
  },
  {
    id: 'anchor-608',
    name: 'Anchor Advance Plus 1.5 sqmm House Wire (90m)',
    slug: 'anchor-advance-plus-1-5-sqmm-house-wire',
    description: 'Single core multi-strand building wire',
    long_description: 'Engineered for lighting and medium load circuits. High oxygen index prevents spread of fire along cable run.',
    price: 24.50,
    category: 'Cables & Wires',
    brand: 'Anchor',
    image_url: '/images/anchor/wire (1).jpg',
    stock: 120,
    specifications: { Brand: 'Anchor', Gauge: '1.5 sqmm', Length: '90m', Type: 'House Wire' },
    created_at: ts,
    updated_at: ts,
  },
  {
    id: 'anchor-609',
    name: 'Anchor Ziva 2.5 sqmm Flame Retardant Wire (90m)',
    slug: 'anchor-ziva-2-5-sqmm-fr-wire',
    description: '2.5 sqmm power wire for sockets and air conditioners',
    long_description: 'Premium multi-strand copper wire rated 22A continuous. Heat resistant to 85°C with high oxygen index insulation.',
    price: 36.00,
    category: 'Cables & Wires',
    brand: 'Anchor',
    image_url: '/images/anchor/wire (1).png',
    stock: 85,
    specifications: { Brand: 'Anchor', Gauge: '2.5 sqmm', Length: '90m', Type: 'FR Wire' },
    created_at: ts,
    updated_at: ts,
  },
  {
    id: 'anchor-610',
    name: 'Anchor Heavy Duty 4.0 sqmm Power Cable (90m)',
    slug: 'anchor-heavy-duty-4-0-sqmm-cable',
    description: '4.0 sqmm high capacity mains and inverter cable',
    long_description: 'Low electrical resistance for heavy loads: main DB distribution, geysers, and EV charger circuits.',
    price: 52.00,
    category: 'Cables & Wires',
    brand: 'Anchor',
    image_url: '/images/anchor/wire (2).jpeg',
    stock: 60,
    specifications: { Brand: 'Anchor', Gauge: '4.0 sqmm', Length: '90m', Type: 'Heavy Duty Cable' },
    created_at: ts,
    updated_at: ts,
  },
  {
    id: 'anchor-611',
    name: 'Anchor Industrial 6.0 sqmm Heavy Load Cable (90m)',
    slug: 'anchor-industrial-6-0-sqmm-cable',
    description: '6.0 sqmm heavy industrial single core cable',
    long_description: 'Sub-main power feeds, heavy motor loads, and industrial grade power boards with near-zero voltage drop.',
    price: 78.00,
    category: 'Cables & Wires',
    brand: 'Anchor',
    image_url: '/images/anchor/wire (2).jpg',
    stock: 45,
    specifications: { Brand: 'Anchor', Gauge: '6.0 sqmm', Length: '90m', Type: 'Industrial Cable' },
    created_at: ts,
    updated_at: ts,
  },
  {
    id: 'anchor-612',
    name: 'Anchor 3-Core Flat Submersible Cable',
    slug: 'anchor-3-core-flat-submersible-cable',
    description: 'Waterproof 3-core flat submersible pump cable',
    long_description: 'Special grade PVC sheathed flexible flat cable. Resistant to water abrasion, moisture, and extreme temperatures.',
    price: 65.00,
    category: 'Cables & Wires',
    brand: 'Anchor',
    image_url: '/images/anchor/wire (3).jpg',
    stock: 40,
    specifications: { Brand: 'Anchor', Type: '3-Core Flat', Use: 'Submersible Pumps' },
    created_at: ts,
    updated_at: ts,
  },
  {
    id: 'anchor-613',
    name: 'Anchor HR-FRLSH Heat Resistant Wire (90m)',
    slug: 'anchor-hr-frlsh-heat-resistant-wire',
    description: 'Heat resistant low smoke halogen-free wire',
    long_description: 'HR-FRLSH copper cable for critical safety installations: hospitals, data centres, and high-rise buildings.',
    price: 42.00,
    category: 'Cables & Wires',
    brand: 'Anchor',
    image_url: '/images/anchor/wire (4).jpg',
    stock: 70,
    specifications: { Brand: 'Anchor', Grade: 'HR-FRLSH', Length: '90m', Type: 'Safety Wire' },
    created_at: ts,
    updated_at: ts,
  },
  {
    id: 'anchor-614',
    name: 'Anchor Armoured Mains Cable',
    slug: 'anchor-armoured-mains-cable',
    description: 'Steel wire armoured underground distribution cable',
    long_description: 'Maximum mechanical protection for underground and outdoor power distribution networks. Double PVC sheathed.',
    price: 95.00,
    category: 'Cables & Wires',
    brand: 'Anchor',
    image_url: '/images/anchor/wire.png',
    stock: 35,
    specifications: { Brand: 'Anchor', Type: 'Armoured Cable', Use: 'Underground / Main Incoming' },
    created_at: ts,
    updated_at: ts,
  },
  {
    id: 'anchor-615',
    name: 'Anchor FR Wire 1.5 sqmm (Red, 90m)',
    slug: 'anchor-fr-wire-1-5-red',
    description: 'Red colour-coded live wire for circuit identification',
    long_description: 'Flame retardant copper wire with ISI-compliant colour coding. Red sheath for live/phase wire circuits.',
    price: 25.00,
    category: 'Cables & Wires',
    brand: 'Anchor',
    image_url: '/images/anchor wires and cables/images.jfif',
    stock: 100,
    specifications: { Brand: 'Anchor', Gauge: '1.5 sqmm', Colour: 'Red (Live)', Type: 'FR Wire' },
    created_at: ts,
    updated_at: ts,
  },
  {
    id: 'anchor-616',
    name: 'Anchor FR Wire 1.5 sqmm (Green, 90m)',
    slug: 'anchor-fr-wire-1-5-green',
    description: 'Green colour-coded earth wire for safety grounding',
    long_description: 'ISI certified earth/ground wire. Green-yellow dual sheath per IEC 60446 colour coding standard.',
    price: 25.00,
    category: 'Cables & Wires',
    brand: 'Anchor',
    image_url: '/images/anchor wires and cables/images (1).jfif',
    stock: 100,
    specifications: { Brand: 'Anchor', Gauge: '1.5 sqmm', Colour: 'Green (Earth)', Type: 'FR Wire' },
    created_at: ts,
    updated_at: ts,
  },
  {
    id: 'anchor-617',
    name: 'Anchor FR Wire 2.5 sqmm (Black, 90m)',
    slug: 'anchor-fr-wire-2-5-black',
    description: 'Black neutral wire for power circuits',
    long_description: 'High purity copper conductor with black PVC insulation for neutral conductors in single and three-phase circuits.',
    price: 36.00,
    category: 'Cables & Wires',
    brand: 'Anchor',
    image_url: '/images/anchor wires and cables/images (2).jfif',
    stock: 90,
    specifications: { Brand: 'Anchor', Gauge: '2.5 sqmm', Colour: 'Black (Neutral)', Type: 'FR Wire' },
    created_at: ts,
    updated_at: ts,
  },
  {
    id: 'anchor-618',
    name: 'Anchor Multi-Core Flex Cable 3-Core 1.5 sqmm',
    slug: 'anchor-3-core-flex-1-5',
    description: '3-core flexible cable for portable appliances',
    long_description: 'Flexible multi-strand 3-core cable for extension cords, portable tools, and small appliance connections.',
    price: 48.00,
    category: 'Cables & Wires',
    brand: 'Anchor',
    image_url: '/images/anchor wires and cables/images (3).jfif',
    stock: 65,
    specifications: { Brand: 'Anchor', Type: '3-Core Flex', Gauge: '1.5 sqmm', Use: 'Portable Appliances' },
    created_at: ts,
    updated_at: ts,
  },
];

// ─── HAVELLS — switches + wires ───────────────────────────────────────────────
const havellsSwitchImages = [
  '/images/havells1/images.jfif',
  '/images/havells1/images (1).jfif',
  '/images/havells1/images (2).jfif',
  '/images/havells1/images (3).jfif',
  '/images/havells1/images (4).jfif',
  '/images/havells1/images (5).jfif',
  '/images/havells1/images (6).jfif',
  '/images/havells1/images (7).jfif',
  '/images/havells1/images (8).jfif',
  '/images/havells1/images (9).jfif',
  '/images/havells1/images (10).jfif',
  '/images/havells1/images (11).jfif',
  '/images/havells1/images (12).jfif',
  '/images/havells1/images (13).jfif',
  '/images/havells1/images (14).jfif',
  '/images/havells1/images (15).jfif',
];

const havellsSwitchNames = [
  'Havells Reo 6A 1-Way Switch',
  'Havells Reo 10A 2-Way Switch',
  'Havells Reo 16A Power Switch',
  'Havells Reo 16A 3-Pin Socket',
  'Havells Reo Bell Push Module',
  'Havells Reo Fan Regulator',
  'Havells Reo USB Charger Socket',
  'Havells Reo Dimmer 200W',
  'Havells Reo TV/SAT Socket',
  'Havells Oro 6A 1-Way Switch',
  'Havells Oro 10A 2-Way Switch',
  'Havells Oro 16A Power Socket',
  'Havells Oro Bell Push',
  'Havells Oro Fan Regulator',
  'Havells Oro USB Type-C Socket',
  'Havells Oro 2M Cover Plate',
];

const havellsWireImages = [
  '/images/havells wires and cables/05-sqmm-havells-electrical-wi-20260123141315861.webp',
  '/images/havells wires and cables/images.jfif',
  '/images/havells wires and cables/images.png',
  '/images/havells wires and cables/images (1).jfif',
  '/images/havells wires and cables/images (1).png',
  '/images/havells wires and cables/images (2).jfif',
  '/images/havells wires and cables/images (3).jfif',
  '/images/havells wires and cables/images (4).jfif',
  '/images/havells wires and cables/images (5).jfif',
  '/images/havells wires and cables/images (6).jfif',
  '/images/havells wires and cables/images (7).jfif',
  '/images/havells wires and cables/images (8).jfif',
];

const havellsWireNames = [
  'Havells Life Line Plus 0.5 sqmm FR Wire (90m)',
  'Havells Life Line Plus 1.0 sqmm FR Wire (90m)',
  'Havells Life Line Plus 1.5 sqmm FR Wire (90m)',
  'Havells Life Line Plus 2.5 sqmm FR Wire (90m)',
  'Havells Life Line Plus 4.0 sqmm FR Wire (90m)',
  'Havells Rr-Hrfr 1.5 sqmm House Wire (90m)',
  'Havells Rr-Hrfr 2.5 sqmm House Wire (90m)',
  'Havells Rr-Hrfr 4.0 sqmm House Wire (90m)',
  'Havells Flexible 3-Core 1.5 sqmm Cable',
  'Havells Submersible 3-Core 2.5 sqmm Cable',
  'Havells 6.0 sqmm Industrial Cable (90m)',
  'Havells Armoured Sub-Main Cable 4.0 sqmm',
];

const havellsProducts: Product[] = [
  ...havellsSwitchImages.map((img, i) => ({
    id: `havells-sw-${700 + i}`,
    name: havellsSwitchNames[i],
    slug: `havells-switch-${700 + i}`,
    description: 'Reliable modular switch engineered for Indian conditions',
    long_description: 'Havells Reo/Oro modular switch with ISI certification, silver alloy contacts, and high-impact polycarbonate housing rated for 100,000 operations.',
    price: parseFloat((1.80 + i * 0.35).toFixed(2)),
    category: 'Switches & Sockets' as const,
    brand: 'Havells',
    image_url: img,
    stock: 80 + i * 10,
    specifications: { Brand: 'Havells', Rating: i % 3 === 0 ? '16A' : '10A', Type: 'Modular', Series: i < 8 ? 'Reo' : 'Oro' },
    created_at: ts,
    updated_at: ts,
  })),
  ...havellsWireImages.map((img, i) => ({
    id: `havells-wr-${720 + i}`,
    name: havellsWireNames[i],
    slug: `havells-wire-${720 + i}`,
    description: 'HRFR PVC insulated copper wire for residential wiring',
    long_description: 'Havells Life Line Plus wire with high purity copper conductor, flame retardant HRFR insulation, and heat resistance up to 90°C.',
    price: parseFloat((18.00 + i * 6.50).toFixed(2)),
    category: 'Cables & Wires' as const,
    brand: 'Havells',
    image_url: img,
    stock: 70 + i * 8,
    specifications: { Brand: 'Havells', Type: 'FR Wire', Length: '90m', Series: 'Life Line Plus' },
    created_at: ts,
    updated_at: ts,
  })),
];

// ─── SCHNEIDER ELECTRIC (14 images) ──────────────────────────────────────────
const schneiderImages = [
  '/images/schneider electrics/schneider-unica-pure-modular-switch.jpeg',
  '/images/schneider electrics/6-a-schneider-unica-pure-modul-20260407004713100.webp',
  '/images/schneider electrics/6a-schneider-unica-pure-modula-20260127190551313.webp',
  '/images/schneider electrics/schneider electrics.webp',
  '/images/schneider electrics/product-jpeg.jpg',
  '/images/schneider electrics/product-jpeg.jfif',
  '/images/schneider electrics/96157933_3564178430265850_580540060701556736_n.webp',
  '/images/schneider electrics/images.jfif',
  '/images/schneider electrics/images (1).jfif',
  '/images/schneider electrics/images (2).jfif',
  '/images/schneider electrics/images (3).jfif',
  '/images/schneider electrics/images (4).jfif',
  '/images/schneider electrics/images (5).jfif',
  '/images/schneider electrics/images (6).jfif',
];

const schneiderNames = [
  'Schneider Unica Pure 6A Modular Switch',
  'Schneider Unica Pure 10A 1-Way Switch',
  'Schneider Unica Pure 16A Power Switch',
  'Schneider Zencelo 6A Full-Flat Switch',
  'Schneider Zencelo 16A Power Socket',
  'Schneider AvatarOn 10A 2-Way Switch',
  'Schneider AvatarOn USB Type-C Socket',
  'Schneider Unica Pure Bell Push',
  'Schneider Unica Pure Fan Regulator',
  'Schneider Zencelo Dimmer 300W',
  'Schneider AvatarOn 16A 3-Pin Socket',
  'Schneider Unica Pure TV/SAT Socket',
  'Schneider Zencelo 2M Cover Plate',
  'Schneider Unica Pure Blank Module',
];

const schneiderProducts: Product[] = schneiderImages.map((img, i) => ({
  id: `schneider-${800 + i}`,
  name: schneiderNames[i],
  slug: `schneider-product-${800 + i}`,
  description: 'Full-flat switch mechanism from Schneider Electric',
  long_description: "Schneider Electric Unica Pure / Zencelo series. World-class mechanical precision, full-flat rocker, and consistent actuation force rated for 100,000 operations.",
  price: parseFloat((5.00 + i * 0.60).toFixed(2)),
  category: 'Switches & Sockets' as const,
  brand: 'Schneider Electric',
  image_url: img,
  stock: 80 + i * 7,
  specifications: { Brand: 'Schneider Electric', Rating: i % 3 === 0 ? '16A' : '10A', Type: 'Full-Flat Modular', Series: i < 5 ? 'Unica Pure' : i < 9 ? 'Zencelo' : 'AvatarOn' },
  created_at: ts,
  updated_at: ts,
}));

// ─── YALE (26 smart home images) ─────────────────────────────────────────────
const yaleImages = Array.from({ length: 26 }, (_, i) => {
  if (i === 0) return '/images/yale fans,lights,smart locker/images.jfif';
  if (i === 24) return '/images/yale fans,lights,smart locker/images (40).jfif';
  return `/images/yale fans,lights,smart locker/images (${i}).jfif`;
});

const yaleTypes = [
  'Smart Door Lock Biometric', 'Smart Door Lock PIN', 'Smart Deadbolt WiFi', 'Smart Padlock',
  'Digital Door Viewer', 'Smart Door Handle Lock', 'Smart Safe Medium', 'Smart Safe Large',
  'Smart Cabinet Lock', 'Smart Glass Door Lock', 'Smart Gate Lock', 'Smart Fingerprint Lock',
  'Smart RFID Door Lock', 'Smart Bluetooth Lock', 'Smart Mortise Lock', 'Smart Rim Lock',
  'Smart Lock Battery Pack', 'Smart Access Controller', 'Smart Doorbell Camera', 'Smart Indoor Camera',
  'Smart Outdoor Camera', 'Smart Alarm Sensor', 'Smart Motion Detector', 'Smart Door Sensor',
  'Smart Keypad Controller', 'Smart Home Hub',
];

const yaleProducts: Product[] = yaleImages.map((img, i) => ({
  id: `yale-${900 + i}`,
  name: `Yale ${yaleTypes[i] ?? 'Smart Security Device'} ${i + 1}`,
  slug: `yale-smart-${900 + i}`,
  description: "World's most trusted smart security for modern homes",
  long_description: "Yale smart security product. Biometric fingerprint, RFID card, PIN, and mobile app access in one device. AES-256 encrypted wireless communication.",
  price: parseFloat((120.00 + i * 18.00).toFixed(2)),
  category: 'Smart Home' as const,
  brand: 'Yale',
  image_url: img,
  stock: 15 + i * 2,
  specifications: { Brand: 'Yale', Type: yaleTypes[i]?.split(' ')[1] ?? 'Smart Lock', Connectivity: i % 3 === 0 ? 'WiFi' : i % 3 === 1 ? 'Bluetooth' : 'Zigbee', Series: 'YDD Series' },
  created_at: ts,
  updated_at: ts,
}));

// ─── LUKER (41 smart home images) ────────────────────────────────────────────
const lukerImages = [
  '/images/luker fans,lights,smart locker/61IUjar0rnL._AC_UF350,350_QL80_.jpg',
  '/images/luker fans,lights,smart locker/images.jfif',
  ...Array.from({ length: 39 }, (_, i) => `/images/luker fans,lights,smart locker/images (${i + 1}).jfif`),
];

const lukerTypes = [
  'LED Panel 15W', 'LED Downlight 9W', 'LED Batten 20W', 'LED Spotlight 7W', 'LED Strip Controller',
  'Ceiling Fan 48in', 'Ceiling Fan 56in', 'Pedestal Fan', 'Wall Fan', 'Exhaust Fan 6in',
  'Smart LED Bulb 9W', 'Smart LED Bulb 12W', 'Smart LED Panel 18W', 'Smart Dimmer Switch', 'Smart Fan Regulator',
  'LED Street Light 30W', 'LED Flood Light 50W', 'LED High Bay 100W', 'LED Track Light 12W', 'LED COB Downlight',
  'Smart Switch 1-Gang', 'Smart Switch 2-Gang', 'Smart Switch 3-Gang', 'Smart Socket WiFi', 'Smart Power Strip',
  'Smart Home Hub', 'Smart IR Blaster', 'Smart Energy Monitor', 'Smart Surge Protector', 'Smart Timer Switch',
  'LED Emergency Light', 'LED Exit Sign', 'LED Panel 24W Round', 'LED Slim Panel 36W', 'LED Surface Panel 12W',
  'Fan Coil Unit Controller', 'Smart Thermostat', 'Smart HVAC Controller', 'LED Grow Light', 'LED Aquarium Light',
  'Smart Light Sensor',
];

const lukerProducts: Product[] = lukerImages.map((img, i) => ({
  id: `luker-${1100 + i}`,
  name: `Luker ${lukerTypes[i] ?? 'Smart Home Device'} ${i + 1}`,
  slug: `luker-smart-${1100 + i}`,
  description: 'Energy-efficient smart lighting and home control',
  long_description: 'Luker smart home product with BEE star rated energy efficiency, WiFi/Bluetooth control via Luker Smart app, and compatible with Alexa and Google Home.',
  price: parseFloat((8.00 + i * 3.20).toFixed(2)),
  category: 'Smart Home' as const,
  brand: 'Luker',
  image_url: img,
  stock: 100 + i * 5,
  specifications: { Brand: 'Luker', Type: lukerTypes[i]?.split(' ')[0] ?? 'LED', Connectivity: i % 2 === 0 ? 'WiFi' : 'Bluetooth', Series: 'Smart Series' },
  created_at: ts,
  updated_at: ts,
}));

// ─── HOME THEATRE (9 images) ──────────────────────────────────────────────────
const homeTheatreProducts: Product[] = [
  {
    id: 'ht-1200',
    name: 'Klipsch Reference 5.2 Home Theatre System',
    slug: 'klipsch-reference-5-2-home-theatre',
    description: '5.2 ch Klipsch Reference floor system with dual subwoofers',
    long_description: 'Complete Klipsch Reference home theatre package. Tractrix horn-loaded tweeters, copper-spun woofers, and dual 10-inch subwoofers deliver cinema-grade dynamics.',
    price: 2499.00,
    category: 'Home Theatre & Audio' as const,
    brand: 'Klipsch',
    image_url: '/images/Home theater/klipsch-reference-5-2-home-theater-system-620.jpg',
    stock: 5,
    specifications: { Brand: 'Klipsch', System: '5.2 Channel', Tweeter: 'Tractrix Horn', Woofer: '6.5 inch Copper', Subwoofer: '10 inch Dual' },
    created_at: ts,
    updated_at: ts,
  },
  {
    id: 'ht-1201',
    name: 'Focal Sopra No.3 Home Cinema 7.1 Package',
    slug: 'focal-sopra-no3-home-cinema-7-1',
    description: 'Premium Focal Sopra 7.1 audiophile cinema system',
    long_description: 'Focal Sopra No.3 floorstanding speakers with matched centre, surround, and height channels. W-cone and Beryllium tweeter technology for transparent reproduction.',
    price: 8999.00,
    category: 'Home Theatre & Audio' as const,
    brand: 'Focal',
    image_url: '/images/Home theater/focal-sopra-no3-home-cinema-7-1-speaker-package-500x500.webp',
    stock: 2,
    specifications: { Brand: 'Focal', System: '7.1 Channel', Tweeter: 'Beryllium', Woofer: 'W-Cone', Crossover: 'Active 3-Way' },
    created_at: ts,
    updated_at: ts,
  },
  {
    id: 'ht-1202',
    name: 'Professional AV Receiver 9.2 Channel',
    slug: 'av-receiver-9-2-channel',
    description: '9.2 ch Dolby Atmos/DTS:X AV receiver',
    long_description: '9.2 channel AV receiver with 8K HDMI 2.1, Dolby Atmos, DTS:X, IMAX Enhanced, and 120W per channel output. Compatible with all major smart home platforms.',
    price: 1599.00,
    category: 'Home Theatre & Audio' as const,
    brand: 'Marantz',
    image_url: '/images/Home theater/1200Wx1200H_39d6a9f7-df0a-4d8c-b6d4-70d31fe15919_1200x630.webp',
    stock: 8,
    specifications: { Brand: 'Marantz', Channels: '9.2', Power: '120W × 9', HDMI: '8K / HDMI 2.1', Formats: 'Atmos / DTS:X' },
    created_at: ts,
    updated_at: ts,
  },
  {
    id: 'ht-1203',
    name: 'Home Theatre Speaker System 5.1',
    slug: 'home-theatre-speaker-system-5-1',
    description: 'Complete 5.1 passive speaker system for home cinema',
    long_description: 'Full 5.1 passive speaker package. 2× floorstanding, 1× centre, 2× bookshelf surrounds, 1× 12-inch subwoofer. Optimised for living room acoustics.',
    price: 899.00,
    category: 'Home Theatre & Audio' as const,
    brand: 'Home Theatre',
    image_url: '/images/Home theater/images.jfif',
    stock: 12,
    specifications: { System: '5.1 Channel', Subwoofer: '12 inch', Tweeter: '1 inch Dome', Woofer: '6.5 inch' },
    created_at: ts,
    updated_at: ts,
  },
  {
    id: 'ht-1204',
    name: 'In-Ceiling Atmos Speaker Pair 8 inch',
    slug: 'in-ceiling-atmos-speaker-pair-8-inch',
    description: 'Architectural 8-inch in-ceiling Atmos speaker pair',
    long_description: 'Flush-mount Dolby Atmos height channel speakers. 8-inch low-frequency driver, pivoting tweeter, and paintable grille for invisible installation.',
    price: 349.00,
    category: 'Home Theatre & Audio' as const,
    brand: 'Home Theatre',
    image_url: '/images/Home theater/images (1).jfif',
    stock: 20,
    specifications: { Type: 'In-Ceiling', Driver: '8 inch', Use: 'Dolby Atmos Height', Installation: 'Flush Mount' },
    created_at: ts,
    updated_at: ts,
  },
  {
    id: 'ht-1205',
    name: '4K Laser Projector UST 120 inch',
    slug: '4k-laser-projector-ust-120-inch',
    description: 'Ultra-short throw 4K laser projector for 120-inch screens',
    long_description: '4K UHD laser projector with 3000 ANSI lumens, HDR10+, and ultra-short throw ratio. Projects 120-inch image from 25cm distance. Built-in Dolby Digital decoder.',
    price: 2999.00,
    category: 'Home Theatre & Audio' as const,
    brand: 'Home Theatre',
    image_url: '/images/Home theater/images (2).jfif',
    stock: 4,
    specifications: { Type: 'UST Laser Projector', Resolution: '4K UHD', Brightness: '3000 ANSI lm', Throw: 'Ultra Short', Screen: '120 inch' },
    created_at: ts,
    updated_at: ts,
  },
  {
    id: 'ht-1206',
    name: 'Acoustic Soundbar Dolby Atmos 3.1.2',
    slug: 'acoustic-soundbar-dolby-atmos-3-1-2',
    description: '3.1.2 ch soundbar with up-firing Atmos drivers',
    long_description: 'Premium soundbar with 3.1.2 Dolby Atmos configuration. Two up-firing height channels, dedicated centre, and wireless 10-inch subwoofer. HDMI ARC/eARC connectivity.',
    price: 649.00,
    category: 'Home Theatre & Audio' as const,
    brand: 'Home Theatre',
    image_url: '/images/Home theater/images (3).jfif',
    stock: 15,
    specifications: { Type: 'Soundbar', Channels: '3.1.2', Format: 'Dolby Atmos', Subwoofer: '10 inch Wireless', HDMI: 'ARC/eARC' },
    created_at: ts,
    updated_at: ts,
  },
  {
    id: 'ht-1207',
    name: 'High-End Floorstanding Speaker Pair',
    slug: 'high-end-floorstanding-speaker-pair',
    description: '3-way floorstanding audiophile tower speakers',
    long_description: 'Reference-grade 3-way floorstanding speaker pair. 10-inch woofer, 5-inch midrange, 1-inch silk dome tweeter. Bi-wireable crossover network, 91dB sensitivity.',
    price: 1299.00,
    category: 'Home Theatre & Audio' as const,
    brand: 'Home Theatre',
    image_url: '/images/Home theater/images (4).jfif',
    stock: 6,
    specifications: { Type: 'Floorstanding', Configuration: '3-Way', Sensitivity: '91 dB', Impedance: '8 Ohm', Woofer: '10 inch' },
    created_at: ts,
    updated_at: ts,
  },
  {
    id: 'ht-1208',
    name: 'ALR Motorised Projection Screen 120 inch 16:9',
    slug: 'alr-motorised-projection-screen-120',
    description: 'Ambient light rejecting motorised screen 120 inch',
    long_description: 'Motorised ALR projection screen with ultra-black backing and micro-structure surface. Rejects 95% ambient light. Electric drop with remote and RS232 control.',
    price: 599.00,
    category: 'Home Theatre & Audio' as const,
    brand: 'Home Theatre',
    image_url: '/images/Home theater/images (5).jfif',
    stock: 10,
    specifications: { Type: 'ALR Motorised Screen', Size: '120 inch 16:9', Gain: '1.0', Ambient: 'Light Rejecting', Control: 'Remote + RS232' },
    created_at: ts,
    updated_at: ts,
  },
];

// ─── EXPORTS ──────────────────────────────────────────────────────────────────
export const EXPANDED_PRODUCTS: Product[] = [
  ...anchorProducts,
  ...kolorsProducts,
  ...legrandProducts,
  ...norisysProducts,
  ...panasonicProducts,
  ...finolexProducts,
  ...havellsProducts,
  ...schneiderProducts,
  ...yaleProducts,
  ...lukerProducts,
  ...homeTheatreProducts,
];

export const PRODUCTS_BY_BRAND = {
  anchor: anchorProducts,
  kolors: kolorsProducts,
  legrand: legrandProducts,
  norisys: norisysProducts,
  panasonic: panasonicProducts,
  finolex: finolexProducts,
  havells: havellsProducts,
  schneider: schneiderProducts,
  yale: yaleProducts,
  luker: lukerProducts,
  homeTheatre: homeTheatreProducts,
};
