import type { Product } from '@/types';
import { EXPANDED_PRODUCTS } from './expanded-products';

export const SAMPLE_PRODUCTS: Product[] = [
  // Include all expanded brand products (73 products total: 21 Kolors + 17 Legrand + 19 Norisys + 7 Panasonic + 9 Finolex)
  ...EXPANDED_PRODUCTS,
  
  // Original products for other brands
  // Switches and accessories
  {
    id: 'prd-100',
    name: 'Anchor Penta 6A Switch',
    slug: 'anchor-penta-6a-switch',
    description: 'Durable 6A 1-way switch',
    long_description: 'Durable 6A 1-way switch. Authentic Anchor product.',
    price: 1.50,
    category: 'Switches & Sockets',
    brand: 'Anchor',
    image_url: '/store-photos/photo-11.jpeg',
    stock: 250,
    specifications: { 'Brand': 'Anchor', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-101',
    name: 'Panasonic Roma Plus 16A Socket',
    slug: 'panasonic-roma-plus-16a-socket',
    description: '16A 3-pin socket with safety shutter',
    long_description: '16A 3-pin socket with safety shutter. Authentic Panasonic product.',
    price: 3.20,
    category: 'Switches & Sockets',
    brand: 'Panasonic',
    image_url: '/images/panasonic/switch (3).png',
    stock: 150,
    specifications: { 'Brand': 'Panasonic', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-102',
    name: 'Kolors Krest Modular Switch',
    slug: 'kolors-krest-modular-switch',
    description: 'Premium modular switch',
    long_description: 'Premium modular switch. Authentic Kolors product.',
    price: 2.10,
    category: 'Switches & Sockets',
    brand: 'Kolors',
    image_url: '/images/kolors/switch13.jpeg',
    stock: 300,
    specifications: { 'Brand': 'Kolors', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-103',
    name: 'Legrand Mylinc 2-Way Switch',
    slug: 'legrand-mylinc-2-way-switch',
    description: '10A 2-way modular switch',
    long_description: '10A 2-way modular switch. Authentic Legrand product.',
    price: 4.00,
    category: 'Switches & Sockets',
    brand: 'Legrand',
    image_url: '/images/legrand/switch2.jpeg',
    stock: 180,
    specifications: { 'Brand': 'Legrand', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-104',
    name: 'Norisys Cube 6A Switch',
    slug: 'norisys-cube-6a-switch',
    description: 'Elegant modular switch',
    long_description: 'Elegant modular switch. Authentic Norisys product.',
    price: 3.50,
    category: 'Switches & Sockets',
    brand: 'Norisys',
    image_url: '/images/norisys/switch (16).jpeg',
    stock: 220,
    specifications: { 'Brand': 'Norisys', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-105',
    name: 'Schneider Zencelo Flat Switch',
    slug: 'schneider-zencelo-flat-switch',
    description: 'Full-flat switch mechanism',
    long_description: 'Full-flat switch mechanism. Authentic Schneider Electric product.',
    price: 5.50,
    category: 'Switches & Sockets',
    brand: 'Schneider Electric',
    image_url: '/store-photos/photo-02.jpeg',
    stock: 140,
    specifications: { 'Brand': 'Schneider Electric', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-106',
    name: 'Finolex 16A Modular Socket',
    slug: 'finolex-16a-modular-socket',
    description: 'Heavy duty 16A socket',
    long_description: 'Heavy duty 16A socket. Authentic Finolex product.',
    price: 3.80,
    category: 'Switches & Sockets',
    brand: 'Finolex',
    image_url: '/store-photos/photo-03.jpeg',
    stock: 160,
    specifications: { 'Brand': 'Finolex', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-107',
    name: 'Hi-Fi Gold Switch',
    slug: 'hi-fi-gold-switch',
    description: 'Cost effective 6A switch',
    long_description: 'Cost effective 6A switch. Authentic Hi-Fi product.',
    price: 1.20,
    category: 'Switches & Sockets',
    brand: 'Hi-Fi',
    image_url: '/store-photos/photo-04.jpeg',
    stock: 400,
    specifications: { 'Brand': 'Hi-Fi', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-108',
    name: 'Havells Reo Switch',
    slug: 'havells-reo-switch',
    description: 'Reliable 6A switch',
    long_description: 'Reliable 6A switch. Authentic Havells product.',
    price: 1.80,
    category: 'Switches & Sockets',
    brand: 'Havells',
    image_url: '/store-photos/photo-05.jpeg',
    stock: 350,
    specifications: { 'Brand': 'Havells', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-109',
    name: 'Crabtree Murano 16A Socket',
    slug: 'crabtree-murano-16a-socket',
    description: 'Luxury 16A socket',
    long_description: 'Luxury 16A socket. Authentic Crabtree product.',
    price: 4.50,
    category: 'Switches & Sockets',
    brand: 'Crabtree',
    image_url: '/store-photos/photo-06.jpeg',
    stock: 120,
    specifications: { 'Brand': 'Crabtree', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  
  // Wires and cables
  {
    id: 'prd-110',
    name: 'Finolex 2.5 sqmm FR Wire',
    slug: 'finolex-2-5-sqmm-fr-wire',
    description: 'Flame retardant 90m coil',
    long_description: 'Flame retardant 90m coil. Authentic Finolex product.',
    price: 25.00,
    category: 'Cables & Wires',
    brand: 'Finolex',
    image_url: '/store-photos/photo-14.jpeg',
    stock: 80,
    specifications: { 'Brand': 'Finolex', 'Category': 'Cables & Wires' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-111',
    name: 'Havells Life Line Plus 1.5 sqmm',
    slug: 'havells-life-line-plus-1-5-sqmm',
    description: 'HRFR PVC insulated wire 90m',
    long_description: 'HRFR PVC insulated wire 90m. Authentic Havells product.',
    price: 18.00,
    category: 'Cables & Wires',
    brand: 'Havells',
    image_url: '/store-photos/photo-01.jpeg',
    stock: 110,
    specifications: { 'Brand': 'Havells', 'Category': 'Cables & Wires' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-112',
    name: 'Anchor Advantge 4.0 sqmm',
    slug: 'anchor-advantge-4-0-sqmm',
    description: 'Heavy duty FR wire 90m',
    long_description: 'Heavy duty FR wire 90m. Authentic Anchor product.',
    price: 35.00,
    category: 'Cables & Wires',
    brand: 'Anchor',
    image_url: '/store-photos/photo-02.jpeg',
    stock: 60,
    specifications: { 'Brand': 'Anchor', 'Category': 'Cables & Wires' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Fans, lights, smart lock
  {
    id: 'prd-113',
    name: 'Havells Stealth Air Ceiling Fan',
    slug: 'havells-stealth-air-ceiling-fan',
    description: 'Silent operation aerodynamic blades',
    long_description: 'Silent operation aerodynamic blades. Authentic Havells product.',
    price: 85.00,
    category: 'Smart Home',
    brand: 'Havells',
    image_url: '/store-photos/photo-03.jpeg',
    stock: 45,
    specifications: { 'Brand': 'Havells', 'Category': 'Smart Home' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-114',
    name: 'Luker 15W LED Panel',
    slug: 'luker-15w-led-panel',
    description: 'Recessed LED downlight',
    long_description: 'Recessed LED downlight. Authentic Luker product.',
    price: 12.00,
    category: 'Smart Home',
    brand: 'Luker',
    image_url: '/store-photos/photo-04.jpeg',
    stock: 200,
    specifications: { 'Brand': 'Luker', 'Category': 'Smart Home' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-115',
    name: 'Yale YDD424 Smart Door Lock',
    slug: 'yale-ydd424-smart-door-lock',
    description: 'Biometric and PIN smart lock',
    long_description: 'Biometric and PIN smart lock. Authentic Yale product.',
    price: 250.00,
    category: 'Smart Home',
    brand: 'Yale',
    image_url: '/store-photos/photo-05.jpeg',
    stock: 20,
    specifications: { 'Brand': 'Yale', 'Category': 'Smart Home' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Hometheatre
  {
    id: 'prd-116',
    name: 'LG CineBeam 4K Projector',
    slug: 'lg-cinebeam-4k-projector',
    description: 'Laser 4K UHD smart projector',
    long_description: 'Laser 4K UHD smart projector. Authentic LG product.',
    price: 1499.00,
    category: 'Home Theatre & Audio',
    brand: 'LG',
    image_url: '/store-photos/photo-06.jpeg',
    stock: 12,
    specifications: { 'Brand': 'LG', 'Category': 'Home Theatre & Audio' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-117',
    name: 'Epson Home Cinema 3800',
    slug: 'epson-home-cinema-3800',
    description: '4K PRO-UHD projector',
    long_description: '4K PRO-UHD projector. Authentic Epson product.',
    price: 1299.00,
    category: 'Home Theatre & Audio',
    brand: 'Epson',
    image_url: '/store-photos/photo-07.jpeg',
    stock: 15,
    specifications: { 'Brand': 'Epson', 'Category': 'Home Theatre & Audio' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-118',
    name: 'Sony VPL-VW290ES Projector',
    slug: 'sony-vpl-vw290es-projector',
    description: 'Native 4K SXRD projector',
    long_description: 'Native 4K SXRD projector. Authentic Sony product.',
    price: 3999.00,
    category: 'Home Theatre & Audio',
    brand: 'Sony',
    image_url: '/store-photos/photo-08.jpeg',
    stock: 5,
    specifications: { 'Brand': 'Sony', 'Category': 'Home Theatre & Audio' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-119',
    name: 'Yamaha RX-V6A AV Receiver',
    slug: 'yamaha-rx-v6a-av-receiver',
    description: '7.2 ch 8K AV receiver',
    long_description: '7.2 ch 8K AV receiver. Authentic Yamaha product.',
    price: 649.00,
    category: 'Home Theatre & Audio',
    brand: 'Yamaha',
    image_url: '/store-photos/photo-09.jpeg',
    stock: 18,
    specifications: { 'Brand': 'Yamaha', 'Category': 'Home Theatre & Audio' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-120',
    name: 'Marantz Cinema 50',
    slug: 'marantz-cinema-50',
    description: 'Premium 9.4 ch AV receiver',
    long_description: 'Premium 9.4 ch AV receiver. Authentic Marantz product.',
    price: 1200.00,
    category: 'Home Theatre & Audio',
    brand: 'Marantz',
    image_url: '/store-photos/photo-03.jpeg',
    stock: 10,
    specifications: { 'Brand': 'Marantz', 'Category': 'Home Theatre & Audio' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-121',
    name: 'Tone Winner AT-300 Processor',
    slug: 'tone-winner-at-300-processor',
    description: '16 channel AV processor',
    long_description: '16 channel AV processor. Authentic Tone Winner product.',
    price: 950.00,
    category: 'Home Theatre & Audio',
    brand: 'Tone Winner',
    image_url: '/store-photos/photo-04.jpeg',
    stock: 8,
    specifications: { 'Brand': 'Tone Winner', 'Category': 'Home Theatre & Audio' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-122',
    name: 'Paradigm Premier 800F',
    slug: 'paradigm-premier-800f',
    description: 'Floorstanding loudspeaker',
    long_description: 'Floorstanding loudspeaker. Authentic Paradigm product.',
    price: 1099.00,
    category: 'Home Theatre & Audio',
    brand: 'Paradigm',
    image_url: '/store-photos/photo-05.jpeg',
    stock: 14,
    specifications: { 'Brand': 'Paradigm', 'Category': 'Home Theatre & Audio' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-123',
    name: 'Klipsch RP-8000F',
    slug: 'klipsch-rp-8000f',
    description: 'Reference premiere floorstanding speaker',
    long_description: 'Reference premiere floorstanding speaker. Authentic Klipsch product.',
    price: 899.00,
    category: 'Home Theatre & Audio',
    brand: 'Klipsch',
    image_url: '/store-photos/photo-06.jpeg',
    stock: 22,
    specifications: { 'Brand': 'Klipsch', 'Category': 'Home Theatre & Audio' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-124',
    name: 'OSD Black Series In-Ceiling',
    slug: 'osd-black-series-in-ceiling',
    description: '8-inch Atmos architectural speaker',
    long_description: '8-inch Atmos architectural speaker. Authentic OSD Audio product.',
    price: 120.00,
    category: 'Home Theatre & Audio',
    brand: 'OSD Audio',
    image_url: '/store-photos/photo-07.jpeg',
    stock: 45,
    specifications: { 'Brand': 'OSD Audio', 'Category': 'Home Theatre & Audio' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-125',
    name: 'Tone Winner AD-7300PA+ Amp',
    slug: 'tone-winner-ad-7300pa-amp',
    description: '7 channel power amplifier',
    long_description: '7 channel power amplifier. Authentic Tone Winner product.',
    price: 1100.00,
    category: 'Home Theatre & Audio',
    brand: 'Tone Winner',
    image_url: '/store-photos/photo-08.jpeg',
    stock: 6,
    specifications: { 'Brand': 'Tone Winner', 'Category': 'Home Theatre & Audio' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-126',
    name: 'Liberty 120" Motorized Screen',
    slug: 'liberty-120-motorized-screen',
    description: 'ALR projector screen',
    long_description: 'ALR projector screen. Authentic Liberty product.',
    price: 450.00,
    category: 'Home Theatre & Audio',
    brand: 'Liberty',
    image_url: '/store-photos/photo-09.jpeg',
    stock: 12,
    specifications: { 'Brand': 'Liberty', 'Category': 'Home Theatre & Audio' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // MCB and DB
  {
    id: 'prd-127',
    name: 'IndoAsian Optipro 16A MCB',
    slug: 'indoasian-optipro-16a-mcb',
    description: 'Single pole C-curve MCB',
    long_description: 'Single pole C-curve MCB. Authentic IndoAsian product.',
    price: 4.50,
    category: 'MCB & DB',
    brand: 'IndoAsian',
    image_url: '/store-photos/photo-10.jpeg',
    stock: 120,
    specifications: { 'Brand': 'IndoAsian', 'Category': 'MCB & DB' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-128',
    name: 'Hager Novello 32A DP MCB',
    slug: 'hager-novello-32a-dp-mcb',
    description: 'Double pole circuit breaker',
    long_description: 'Double pole circuit breaker. Authentic Hager product.',
    price: 12.50,
    category: 'MCB & DB',
    brand: 'Hager',
    image_url: '/store-photos/photo-11.jpeg',
    stock: 80,
    specifications: { 'Brand': 'Hager', 'Category': 'MCB & DB' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-129',
    name: 'Legrand 8-Way DB',
    slug: 'legrand-8-way-db',
    description: 'SPN Distribution Board',
    long_description: 'SPN Distribution Board. Authentic Legrand product.',
    price: 45.00,
    category: 'MCB & DB',
    brand: 'Legrand',
    image_url: '/images/legrand/switch.jpeg',
    stock: 35,
    specifications: { 'Brand': 'Legrand', 'Category': 'MCB & DB' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  {
    id: 'prd-1000',
    name: 'Kolors Modular Switch 1',
    slug: 'kolors-1-switch-1786911771593',
    description: 'Premium switch module from Kolors',
    long_description: 'High-quality authentic Kolors switch module, designed for modern interiors.',
    price: 2.47,
    category: 'Switches & Sockets',
    brand: 'Kolors',
    image_url: '/images/kolors/switch.jpg',
    stock: 40,
    specifications: { 'Brand': 'Kolors', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1001',
    name: 'Kolors Modular Switch 2',
    slug: 'kolors-2-switch-1786911771593',
    description: 'Premium switch module from Kolors',
    long_description: 'High-quality authentic Kolors switch module, designed for modern interiors.',
    price: 2.35,
    category: 'Switches & Sockets',
    brand: 'Kolors',
    image_url: '/images/kolors/switch1.jpeg',
    stock: 82,
    specifications: { 'Brand': 'Kolors', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1002',
    name: 'Kolors Modular Switch 3',
    slug: 'kolors-3-switch-1786911771593',
    description: 'Premium switch module from Kolors',
    long_description: 'High-quality authentic Kolors switch module, designed for modern interiors.',
    price: 2.92,
    category: 'Switches & Sockets',
    brand: 'Kolors',
    image_url: '/images/kolors/switch10.jpeg',
    stock: 64,
    specifications: { 'Brand': 'Kolors', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1003',
    name: 'Kolors Modular Switch 4',
    slug: 'kolors-4-switch-1786911771593',
    description: 'Premium switch module from Kolors',
    long_description: 'High-quality authentic Kolors switch module, designed for modern interiors.',
    price: 2.27,
    category: 'Switches & Sockets',
    brand: 'Kolors',
    image_url: '/images/kolors/switch11.jpeg',
    stock: 97,
    specifications: { 'Brand': 'Kolors', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1004',
    name: 'Kolors Modular Switch 5',
    slug: 'kolors-5-switch-1786911771593',
    description: 'Premium switch module from Kolors',
    long_description: 'High-quality authentic Kolors switch module, designed for modern interiors.',
    price: 5.32,
    category: 'Switches & Sockets',
    brand: 'Kolors',
    image_url: '/images/kolors/switch12.jpeg',
    stock: 21,
    specifications: { 'Brand': 'Kolors', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1005',
    name: 'Kolors Modular Switch 7',
    slug: 'kolors-7-switch-1786911771593',
    description: 'Premium switch module from Kolors',
    long_description: 'High-quality authentic Kolors switch module, designed for modern interiors.',
    price: 6.06,
    category: 'Switches & Sockets',
    brand: 'Kolors',
    image_url: '/images/kolors/switch14.jpeg',
    stock: 28,
    specifications: { 'Brand': 'Kolors', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1006',
    name: 'Kolors Modular Switch 8',
    slug: 'kolors-8-switch-1786911771593',
    description: 'Premium switch module from Kolors',
    long_description: 'High-quality authentic Kolors switch module, designed for modern interiors.',
    price: 4.41,
    category: 'Switches & Sockets',
    brand: 'Kolors',
    image_url: '/images/kolors/switch15.jpeg',
    stock: 76,
    specifications: { 'Brand': 'Kolors', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1007',
    name: 'Kolors Modular Switch 9',
    slug: 'kolors-9-switch-1786911771593',
    description: 'Premium switch module from Kolors',
    long_description: 'High-quality authentic Kolors switch module, designed for modern interiors.',
    price: 3.68,
    category: 'Switches & Sockets',
    brand: 'Kolors',
    image_url: '/images/kolors/switch16.jpeg',
    stock: 89,
    specifications: { 'Brand': 'Kolors', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1008',
    name: 'Kolors Modular Switch 10',
    slug: 'kolors-10-switch-1786911771593',
    description: 'Premium switch module from Kolors',
    long_description: 'High-quality authentic Kolors switch module, designed for modern interiors.',
    price: 6.82,
    category: 'Switches & Sockets',
    brand: 'Kolors',
    image_url: '/images/kolors/switch17.jpeg',
    stock: 98,
    specifications: { 'Brand': 'Kolors', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1009',
    name: 'Kolors Modular Switch 11',
    slug: 'kolors-11-switch-1786911771593',
    description: 'Premium switch module from Kolors',
    long_description: 'High-quality authentic Kolors switch module, designed for modern interiors.',
    price: 3.64,
    category: 'Switches & Sockets',
    brand: 'Kolors',
    image_url: '/images/kolors/switch18.jpeg',
    stock: 60,
    specifications: { 'Brand': 'Kolors', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1010',
    name: 'Kolors Modular Switch 12',
    slug: 'kolors-12-switch-1786911771593',
    description: 'Premium switch module from Kolors',
    long_description: 'High-quality authentic Kolors switch module, designed for modern interiors.',
    price: 3.81,
    category: 'Switches & Sockets',
    brand: 'Kolors',
    image_url: '/images/kolors/switch19.jpeg',
    stock: 26,
    specifications: { 'Brand': 'Kolors', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1011',
    name: 'Kolors Modular Switch 13',
    slug: 'kolors-13-switch-1786911771593',
    description: 'Premium switch module from Kolors',
    long_description: 'High-quality authentic Kolors switch module, designed for modern interiors.',
    price: 5.32,
    category: 'Switches & Sockets',
    brand: 'Kolors',
    image_url: '/images/kolors/switch2.jpeg',
    stock: 41,
    specifications: { 'Brand': 'Kolors', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1012',
    name: 'Kolors Modular Switch 14',
    slug: 'kolors-14-switch-1786911771593',
    description: 'Premium switch module from Kolors',
    long_description: 'High-quality authentic Kolors switch module, designed for modern interiors.',
    price: 5.81,
    category: 'Switches & Sockets',
    brand: 'Kolors',
    image_url: '/images/kolors/switch3.jpeg',
    stock: 46,
    specifications: { 'Brand': 'Kolors', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1013',
    name: 'Kolors Modular Switch 15',
    slug: 'kolors-15-switch-1786911771593',
    description: 'Premium switch module from Kolors',
    long_description: 'High-quality authentic Kolors switch module, designed for modern interiors.',
    price: 4.02,
    category: 'Switches & Sockets',
    brand: 'Kolors',
    image_url: '/images/kolors/switch4.jpeg',
    stock: 66,
    specifications: { 'Brand': 'Kolors', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1014',
    name: 'Kolors Modular Switch 16',
    slug: 'kolors-16-switch-1786911771593',
    description: 'Premium switch module from Kolors',
    long_description: 'High-quality authentic Kolors switch module, designed for modern interiors.',
    price: 4.94,
    category: 'Switches & Sockets',
    brand: 'Kolors',
    image_url: '/images/kolors/switch6.jpeg',
    stock: 83,
    specifications: { 'Brand': 'Kolors', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1015',
    name: 'Kolors Modular Switch 17',
    slug: 'kolors-17-switch-1786911771593',
    description: 'Premium switch module from Kolors',
    long_description: 'High-quality authentic Kolors switch module, designed for modern interiors.',
    price: 4.32,
    category: 'Switches & Sockets',
    brand: 'Kolors',
    image_url: '/images/kolors/switch7.jpeg',
    stock: 10,
    specifications: { 'Brand': 'Kolors', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1016',
    name: 'Kolors Modular Switch 18',
    slug: 'kolors-18-switch-1786911771593',
    description: 'Premium switch module from Kolors',
    long_description: 'High-quality authentic Kolors switch module, designed for modern interiors.',
    price: 2.81,
    category: 'Switches & Sockets',
    brand: 'Kolors',
    image_url: '/images/kolors/switch8.jpeg',
    stock: 86,
    specifications: { 'Brand': 'Kolors', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1017',
    name: 'Kolors Modular Switch 19',
    slug: 'kolors-19-switch-1786911771593',
    description: 'Premium switch module from Kolors',
    long_description: 'High-quality authentic Kolors switch module, designed for modern interiors.',
    price: 5.85,
    category: 'Switches & Sockets',
    brand: 'Kolors',
    image_url: '/images/kolors/switch9.jpeg',
    stock: 33,
    specifications: { 'Brand': 'Kolors', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1018',
    name: 'Legrand Modular Switch 2',
    slug: 'legrand-2-switch-1786911771593',
    description: 'Premium switch module from Legrand',
    long_description: 'High-quality authentic Legrand switch module, designed for modern interiors.',
    price: 5.97,
    category: 'Switches & Sockets',
    brand: 'Legrand',
    image_url: '/images/legrand/switch1.jpeg',
    stock: 85,
    specifications: { 'Brand': 'Legrand', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1019',
    name: 'Legrand Modular Switch 3',
    slug: 'legrand-3-switch-1786911771593',
    description: 'Premium switch module from Legrand',
    long_description: 'High-quality authentic Legrand switch module, designed for modern interiors.',
    price: 3.90,
    category: 'Switches & Sockets',
    brand: 'Legrand',
    image_url: '/images/legrand/switch10.jpeg',
    stock: 72,
    specifications: { 'Brand': 'Legrand', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1020',
    name: 'Legrand Modular Switch 4',
    slug: 'legrand-4-switch-1786911771593',
    description: 'Premium switch module from Legrand',
    long_description: 'High-quality authentic Legrand switch module, designed for modern interiors.',
    price: 4.78,
    category: 'Switches & Sockets',
    brand: 'Legrand',
    image_url: '/images/legrand/switch11.jpeg',
    stock: 95,
    specifications: { 'Brand': 'Legrand', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1021',
    name: 'Legrand Modular Switch 5',
    slug: 'legrand-5-switch-1786911771593',
    description: 'Premium switch module from Legrand',
    long_description: 'High-quality authentic Legrand switch module, designed for modern interiors.',
    price: 5.89,
    category: 'Switches & Sockets',
    brand: 'Legrand',
    image_url: '/images/legrand/switch12.jpeg',
    stock: 102,
    specifications: { 'Brand': 'Legrand', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1022',
    name: 'Legrand Modular Switch 6',
    slug: 'legrand-6-switch-1786911771593',
    description: 'Premium switch module from Legrand',
    long_description: 'High-quality authentic Legrand switch module, designed for modern interiors.',
    price: 6.80,
    category: 'Switches & Sockets',
    brand: 'Legrand',
    image_url: '/images/legrand/switch13.jpeg',
    stock: 29,
    specifications: { 'Brand': 'Legrand', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1023',
    name: 'Legrand Modular Switch 7',
    slug: 'legrand-7-switch-1786911771593',
    description: 'Premium switch module from Legrand',
    long_description: 'High-quality authentic Legrand switch module, designed for modern interiors.',
    price: 5.98,
    category: 'Switches & Sockets',
    brand: 'Legrand',
    image_url: '/images/legrand/switch14.jpeg',
    stock: 30,
    specifications: { 'Brand': 'Legrand', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1024',
    name: 'Legrand Modular Switch 8',
    slug: 'legrand-8-switch-1786911771593',
    description: 'Premium switch module from Legrand',
    long_description: 'High-quality authentic Legrand switch module, designed for modern interiors.',
    price: 2.13,
    category: 'Switches & Sockets',
    brand: 'Legrand',
    image_url: '/images/legrand/switch15.jpeg',
    stock: 88,
    specifications: { 'Brand': 'Legrand', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1025',
    name: 'Legrand Modular Switch 9',
    slug: 'legrand-9-switch-1786911771593',
    description: 'Premium switch module from Legrand',
    long_description: 'High-quality authentic Legrand switch module, designed for modern interiors.',
    price: 4.56,
    category: 'Switches & Sockets',
    brand: 'Legrand',
    image_url: '/images/legrand/switch16.jpg',
    stock: 61,
    specifications: { 'Brand': 'Legrand', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1026',
    name: 'Legrand Modular Switch 11',
    slug: 'legrand-11-switch-1786911771593',
    description: 'Premium switch module from Legrand',
    long_description: 'High-quality authentic Legrand switch module, designed for modern interiors.',
    price: 6.01,
    category: 'Switches & Sockets',
    brand: 'Legrand',
    image_url: '/images/legrand/switch3.jpeg',
    stock: 85,
    specifications: { 'Brand': 'Legrand', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1027',
    name: 'Legrand Modular Switch 12',
    slug: 'legrand-12-switch-1786911771593',
    description: 'Premium switch module from Legrand',
    long_description: 'High-quality authentic Legrand switch module, designed for modern interiors.',
    price: 3.75,
    category: 'Switches & Sockets',
    brand: 'Legrand',
    image_url: '/images/legrand/switch4.jpeg',
    stock: 35,
    specifications: { 'Brand': 'Legrand', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1028',
    name: 'Legrand Modular Switch 13',
    slug: 'legrand-13-switch-1786911771593',
    description: 'Premium switch module from Legrand',
    long_description: 'High-quality authentic Legrand switch module, designed for modern interiors.',
    price: 6.25,
    category: 'Switches & Sockets',
    brand: 'Legrand',
    image_url: '/images/legrand/switch5.jpeg',
    stock: 42,
    specifications: { 'Brand': 'Legrand', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1029',
    name: 'Legrand Modular Switch 14',
    slug: 'legrand-14-switch-1786911771593',
    description: 'Premium switch module from Legrand',
    long_description: 'High-quality authentic Legrand switch module, designed for modern interiors.',
    price: 2.15,
    category: 'Switches & Sockets',
    brand: 'Legrand',
    image_url: '/images/legrand/switch6.jpeg',
    stock: 16,
    specifications: { 'Brand': 'Legrand', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1030',
    name: 'Legrand Modular Switch 15',
    slug: 'legrand-15-switch-1786911771593',
    description: 'Premium switch module from Legrand',
    long_description: 'High-quality authentic Legrand switch module, designed for modern interiors.',
    price: 2.52,
    category: 'Switches & Sockets',
    brand: 'Legrand',
    image_url: '/images/legrand/switch7.jpeg',
    stock: 77,
    specifications: { 'Brand': 'Legrand', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1031',
    name: 'Legrand Modular Switch 16',
    slug: 'legrand-16-switch-1786911771593',
    description: 'Premium switch module from Legrand',
    long_description: 'High-quality authentic Legrand switch module, designed for modern interiors.',
    price: 6.28,
    category: 'Switches & Sockets',
    brand: 'Legrand',
    image_url: '/images/legrand/switch8.jpeg',
    stock: 108,
    specifications: { 'Brand': 'Legrand', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1032',
    name: 'Legrand Modular Switch 17',
    slug: 'legrand-17-switch-1786911771593',
    description: 'Premium switch module from Legrand',
    long_description: 'High-quality authentic Legrand switch module, designed for modern interiors.',
    price: 4.89,
    category: 'Switches & Sockets',
    brand: 'Legrand',
    image_url: '/images/legrand/switch9.jpeg',
    stock: 91,
    specifications: { 'Brand': 'Legrand', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1033',
    name: 'Norisys Modular Switch 1',
    slug: 'norisys-1-switch-1786911771593',
    description: 'Premium switch module from Norisys',
    long_description: 'High-quality authentic Norisys switch module, designed for modern interiors.',
    price: 2.70,
    category: 'Switches & Sockets',
    brand: 'Norisys',
    image_url: '/images/norisys/switch (1).jpeg',
    stock: 70,
    specifications: { 'Brand': 'Norisys', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1034',
    name: 'Norisys Modular Switch 2',
    slug: 'norisys-2-switch-1786911771593',
    description: 'Premium switch module from Norisys',
    long_description: 'High-quality authentic Norisys switch module, designed for modern interiors.',
    price: 5.23,
    category: 'Switches & Sockets',
    brand: 'Norisys',
    image_url: '/images/norisys/switch (10).jpeg',
    stock: 73,
    specifications: { 'Brand': 'Norisys', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1035',
    name: 'Norisys Modular Switch 3',
    slug: 'norisys-3-switch-1786911771593',
    description: 'Premium switch module from Norisys',
    long_description: 'High-quality authentic Norisys switch module, designed for modern interiors.',
    price: 3.63,
    category: 'Switches & Sockets',
    brand: 'Norisys',
    image_url: '/images/norisys/switch (11).jpeg',
    stock: 66,
    specifications: { 'Brand': 'Norisys', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1036',
    name: 'Norisys Modular Switch 4',
    slug: 'norisys-4-switch-1786911771593',
    description: 'Premium switch module from Norisys',
    long_description: 'High-quality authentic Norisys switch module, designed for modern interiors.',
    price: 3.09,
    category: 'Switches & Sockets',
    brand: 'Norisys',
    image_url: '/images/norisys/switch (12).jpeg',
    stock: 96,
    specifications: { 'Brand': 'Norisys', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1037',
    name: 'Norisys Modular Switch 5',
    slug: 'norisys-5-switch-1786911771593',
    description: 'Premium switch module from Norisys',
    long_description: 'High-quality authentic Norisys switch module, designed for modern interiors.',
    price: 5.81,
    category: 'Switches & Sockets',
    brand: 'Norisys',
    image_url: '/images/norisys/switch (13).jpeg',
    stock: 24,
    specifications: { 'Brand': 'Norisys', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1038',
    name: 'Norisys Modular Switch 6',
    slug: 'norisys-6-switch-1786911771593',
    description: 'Premium switch module from Norisys',
    long_description: 'High-quality authentic Norisys switch module, designed for modern interiors.',
    price: 2.76,
    category: 'Switches & Sockets',
    brand: 'Norisys',
    image_url: '/images/norisys/switch (14).jpeg',
    stock: 55,
    specifications: { 'Brand': 'Norisys', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1039',
    name: 'Norisys Modular Switch 7',
    slug: 'norisys-7-switch-1786911771593',
    description: 'Premium switch module from Norisys',
    long_description: 'High-quality authentic Norisys switch module, designed for modern interiors.',
    price: 3.70,
    category: 'Switches & Sockets',
    brand: 'Norisys',
    image_url: '/images/norisys/switch (15).jpeg',
    stock: 58,
    specifications: { 'Brand': 'Norisys', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1040',
    name: 'Norisys Modular Switch 9',
    slug: 'norisys-9-switch-1786911771593',
    description: 'Premium switch module from Norisys',
    long_description: 'High-quality authentic Norisys switch module, designed for modern interiors.',
    price: 2.50,
    category: 'Switches & Sockets',
    brand: 'Norisys',
    image_url: '/images/norisys/switch (17).jpeg',
    stock: 38,
    specifications: { 'Brand': 'Norisys', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1041',
    name: 'Norisys Modular Switch 10',
    slug: 'norisys-10-switch-1786911771593',
    description: 'Premium switch module from Norisys',
    long_description: 'High-quality authentic Norisys switch module, designed for modern interiors.',
    price: 2.83,
    category: 'Switches & Sockets',
    brand: 'Norisys',
    image_url: '/images/norisys/switch (18).jpeg',
    stock: 105,
    specifications: { 'Brand': 'Norisys', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1042',
    name: 'Norisys Modular Switch 11',
    slug: 'norisys-11-switch-1786911771593',
    description: 'Premium switch module from Norisys',
    long_description: 'High-quality authentic Norisys switch module, designed for modern interiors.',
    price: 2.29,
    category: 'Switches & Sockets',
    brand: 'Norisys',
    image_url: '/images/norisys/switch (19).jpeg',
    stock: 35,
    specifications: { 'Brand': 'Norisys', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1043',
    name: 'Norisys Modular Switch 12',
    slug: 'norisys-12-switch-1786911771593',
    description: 'Premium switch module from Norisys',
    long_description: 'High-quality authentic Norisys switch module, designed for modern interiors.',
    price: 6.32,
    category: 'Switches & Sockets',
    brand: 'Norisys',
    image_url: '/images/norisys/switch (2).jpeg',
    stock: 94,
    specifications: { 'Brand': 'Norisys', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1044',
    name: 'Norisys Modular Switch 13',
    slug: 'norisys-13-switch-1786911771593',
    description: 'Premium switch module from Norisys',
    long_description: 'High-quality authentic Norisys switch module, designed for modern interiors.',
    price: 4.73,
    category: 'Switches & Sockets',
    brand: 'Norisys',
    image_url: '/images/norisys/switch (3).jpeg',
    stock: 38,
    specifications: { 'Brand': 'Norisys', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1045',
    name: 'Norisys Modular Switch 14',
    slug: 'norisys-14-switch-1786911771593',
    description: 'Premium switch module from Norisys',
    long_description: 'High-quality authentic Norisys switch module, designed for modern interiors.',
    price: 3.63,
    category: 'Switches & Sockets',
    brand: 'Norisys',
    image_url: '/images/norisys/switch (4).jpeg',
    stock: 36,
    specifications: { 'Brand': 'Norisys', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1046',
    name: 'Norisys Modular Switch 15',
    slug: 'norisys-15-switch-1786911771593',
    description: 'Premium switch module from Norisys',
    long_description: 'High-quality authentic Norisys switch module, designed for modern interiors.',
    price: 3.78,
    category: 'Switches & Sockets',
    brand: 'Norisys',
    image_url: '/images/norisys/switch (5).jpeg',
    stock: 68,
    specifications: { 'Brand': 'Norisys', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1047',
    name: 'Norisys Modular Switch 16',
    slug: 'norisys-16-switch-1786911771593',
    description: 'Premium switch module from Norisys',
    long_description: 'High-quality authentic Norisys switch module, designed for modern interiors.',
    price: 6.05,
    category: 'Switches & Sockets',
    brand: 'Norisys',
    image_url: '/images/norisys/switch (6).jpeg',
    stock: 21,
    specifications: { 'Brand': 'Norisys', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1048',
    name: 'Norisys Modular Switch 17',
    slug: 'norisys-17-switch-1786911771593',
    description: 'Premium switch module from Norisys',
    long_description: 'High-quality authentic Norisys switch module, designed for modern interiors.',
    price: 5.78,
    category: 'Switches & Sockets',
    brand: 'Norisys',
    image_url: '/images/norisys/switch (7).jpeg',
    stock: 20,
    specifications: { 'Brand': 'Norisys', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1049',
    name: 'Norisys Modular Switch 18',
    slug: 'norisys-18-switch-1786911771593',
    description: 'Premium switch module from Norisys',
    long_description: 'High-quality authentic Norisys switch module, designed for modern interiors.',
    price: 4.07,
    category: 'Switches & Sockets',
    brand: 'Norisys',
    image_url: '/images/norisys/switch (8).jpeg',
    stock: 90,
    specifications: { 'Brand': 'Norisys', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1050',
    name: 'Norisys Modular Switch 19',
    slug: 'norisys-19-switch-1786911771593',
    description: 'Premium switch module from Norisys',
    long_description: 'High-quality authentic Norisys switch module, designed for modern interiors.',
    price: 2.96,
    category: 'Switches & Sockets',
    brand: 'Norisys',
    image_url: '/images/norisys/switch (9).jpeg',
    stock: 98,
    specifications: { 'Brand': 'Norisys', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1051',
    name: 'Panasonic Modular Switch 1',
    slug: 'panasonic-1-switch-1786911771593',
    description: 'Premium switch module from Panasonic',
    long_description: 'High-quality authentic Panasonic switch module, designed for modern interiors.',
    price: 5.29,
    category: 'Switches & Sockets',
    brand: 'Panasonic',
    image_url: '/images/panasonic/switch (1).jpeg',
    stock: 28,
    specifications: { 'Brand': 'Panasonic', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1052',
    name: 'Panasonic Modular Switch 2',
    slug: 'panasonic-2-switch-1786911771593',
    description: 'Premium switch module from Panasonic',
    long_description: 'High-quality authentic Panasonic switch module, designed for modern interiors.',
    price: 6.52,
    category: 'Switches & Sockets',
    brand: 'Panasonic',
    image_url: '/images/panasonic/switch (1).jpg',
    stock: 10,
    specifications: { 'Brand': 'Panasonic', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1053',
    name: 'Panasonic Modular Switch 3',
    slug: 'panasonic-3-switch-1786911771593',
    description: 'Premium switch module from Panasonic',
    long_description: 'High-quality authentic Panasonic switch module, designed for modern interiors.',
    price: 5.16,
    category: 'Switches & Sockets',
    brand: 'Panasonic',
    image_url: '/images/panasonic/switch (1).png',
    stock: 100,
    specifications: { 'Brand': 'Panasonic', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1054',
    name: 'Panasonic Modular Switch 4',
    slug: 'panasonic-4-switch-1786911771593',
    description: 'Premium switch module from Panasonic',
    long_description: 'High-quality authentic Panasonic switch module, designed for modern interiors.',
    price: 4.39,
    category: 'Switches & Sockets',
    brand: 'Panasonic',
    image_url: '/images/panasonic/switch (1).webp',
    stock: 101,
    specifications: { 'Brand': 'Panasonic', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1055',
    name: 'Panasonic Modular Switch 5',
    slug: 'panasonic-5-switch-1786911771593',
    description: 'Premium switch module from Panasonic',
    long_description: 'High-quality authentic Panasonic switch module, designed for modern interiors.',
    price: 2.48,
    category: 'Switches & Sockets',
    brand: 'Panasonic',
    image_url: '/images/panasonic/switch (2).jpeg',
    stock: 19,
    specifications: { 'Brand': 'Panasonic', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-1056',
    name: 'Panasonic Modular Switch 6',
    slug: 'panasonic-6-switch-1786911771593',
    description: 'Premium switch module from Panasonic',
    long_description: 'High-quality authentic Panasonic switch module, designed for modern interiors.',
    price: 6.79,
    category: 'Switches & Sockets',
    brand: 'Panasonic',
    image_url: '/images/panasonic/switch (2).png',
    stock: 41,
    specifications: { 'Brand': 'Panasonic', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const HOME_THEATRE_PRODUCTS = SAMPLE_PRODUCTS.filter(
  (p) => p.category === 'Home Theatre & Audio'
);

