import type { Product } from '@/types';

export const SAMPLE_PRODUCTS: Product[] = [
  // Switches and accessories
  {
    id: 'prd-100',
    name: 'Anchor Penta 6A Switch',
    slug: 'anchor-penta-6a-switch',
    description: 'Durable 6A 1-way switch',
    long_description: 'Durable 6A 1-way switch. Authentic Anchor product.',
    price: 1.50,
    category: 'Switches & Sockets',
    brand: 'Anchor',
    image_url: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=800&auto=format&fit=crop',
    stock: 250,
    specifications: { 'Brand': 'Anchor', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-101',
    name: 'Panasonic Roma Plus 16A Socket',
    slug: 'panasonic-roma-plus-16a-socket',
    description: '16A 3-pin socket with safety shutter',
    long_description: '16A 3-pin socket with safety shutter. Authentic Panasonic product.',
    price: 3.20,
    category: 'Switches & Sockets',
    brand: 'Panasonic',
    image_url: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=800&auto=format&fit=crop',
    stock: 150,
    specifications: { 'Brand': 'Panasonic', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-102',
    name: 'Kolors Krest Modular Switch',
    slug: 'kolors-krest-modular-switch',
    description: 'Premium modular switch',
    long_description: 'Premium modular switch. Authentic Kolors product.',
    price: 2.10,
    category: 'Switches & Sockets',
    brand: 'Kolors',
    image_url: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=800&auto=format&fit=crop',
    stock: 300,
    specifications: { 'Brand': 'Kolors', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-103',
    name: 'Legrand Mylinc 2-Way Switch',
    slug: 'legrand-mylinc-2-way-switch',
    description: '10A 2-way modular switch',
    long_description: '10A 2-way modular switch. Authentic Legrand product.',
    price: 4.00,
    category: 'Switches & Sockets',
    brand: 'Legrand',
    image_url: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=800&auto=format&fit=crop',
    stock: 180,
    specifications: { 'Brand': 'Legrand', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-104',
    name: 'Norisys Cube 6A Switch',
    slug: 'norisys-cube-6a-switch',
    description: 'Elegant modular switch',
    long_description: 'Elegant modular switch. Authentic Norisys product.',
    price: 3.50,
    category: 'Switches & Sockets',
    brand: 'Norisys',
    image_url: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=800&auto=format&fit=crop',
    stock: 220,
    specifications: { 'Brand': 'Norisys', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-105',
    name: 'Schneider Zencelo Flat Switch',
    slug: 'schneider-zencelo-flat-switch',
    description: 'Full-flat switch mechanism',
    long_description: 'Full-flat switch mechanism. Authentic Schneider Electric product.',
    price: 5.50,
    category: 'Switches & Sockets',
    brand: 'Schneider Electric',
    image_url: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=800&auto=format&fit=crop',
    stock: 140,
    specifications: { 'Brand': 'Schneider Electric', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-106',
    name: 'Finolex 16A Modular Socket',
    slug: 'finolex-16a-modular-socket',
    description: 'Heavy duty 16A socket',
    long_description: 'Heavy duty 16A socket. Authentic Finolex product.',
    price: 3.80,
    category: 'Switches & Sockets',
    brand: 'Finolex',
    image_url: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=800&auto=format&fit=crop',
    stock: 160,
    specifications: { 'Brand': 'Finolex', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-107',
    name: 'Hi-Fi Gold Switch',
    slug: 'hi-fi-gold-switch',
    description: 'Cost effective 6A switch',
    long_description: 'Cost effective 6A switch. Authentic Hi-Fi product.',
    price: 1.20,
    category: 'Switches & Sockets',
    brand: 'Hi-Fi',
    image_url: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=800&auto=format&fit=crop',
    stock: 400,
    specifications: { 'Brand': 'Hi-Fi', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-108',
    name: 'Havells Reo Switch',
    slug: 'havells-reo-switch',
    description: 'Reliable 6A switch',
    long_description: 'Reliable 6A switch. Authentic Havells product.',
    price: 1.80,
    category: 'Switches & Sockets',
    brand: 'Havells',
    image_url: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=800&auto=format&fit=crop',
    stock: 350,
    specifications: { 'Brand': 'Havells', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-109',
    name: 'Crabtree Murano 16A Socket',
    slug: 'crabtree-murano-16a-socket',
    description: 'Luxury 16A socket',
    long_description: 'Luxury 16A socket. Authentic Crabtree product.',
    price: 4.50,
    category: 'Switches & Sockets',
    brand: 'Crabtree',
    image_url: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=800&auto=format&fit=crop',
    stock: 120,
    specifications: { 'Brand': 'Crabtree', 'Category': 'Switches & Sockets' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  
  // Wires and cables
  {
    id: 'prd-110',
    name: 'Finolex 2.5 sqmm FR Wire',
    slug: 'finolex-2-5-sqmm-fr-wire',
    description: 'Flame retardant 90m coil',
    long_description: 'Flame retardant 90m coil. Authentic Finolex product.',
    price: 25.00,
    category: 'Cables & Wires',
    brand: 'Finolex',
    image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&auto=format&fit=crop',
    stock: 80,
    specifications: { 'Brand': 'Finolex', 'Category': 'Cables & Wires' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-111',
    name: 'Havells Life Line Plus 1.5 sqmm',
    slug: 'havells-life-line-plus-1-5-sqmm',
    description: 'HRFR PVC insulated wire 90m',
    long_description: 'HRFR PVC insulated wire 90m. Authentic Havells product.',
    price: 18.00,
    category: 'Cables & Wires',
    brand: 'Havells',
    image_url: 'https://images.unsplash.com/photo-1606904825846-647eb07f5be2?w=800&auto=format&fit=crop',
    stock: 110,
    specifications: { 'Brand': 'Havells', 'Category': 'Cables & Wires' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-112',
    name: 'Anchor Advantge 4.0 sqmm',
    slug: 'anchor-advantge-4-0-sqmm',
    description: 'Heavy duty FR wire 90m',
    long_description: 'Heavy duty FR wire 90m. Authentic Anchor product.',
    price: 35.00,
    category: 'Cables & Wires',
    brand: 'Anchor',
    image_url: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800&auto=format&fit=crop',
    stock: 60,
    specifications: { 'Brand': 'Anchor', 'Category': 'Cables & Wires' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Fans, lights, smart lock
  {
    id: 'prd-113',
    name: 'Havells Stealth Air Ceiling Fan',
    slug: 'havells-stealth-air-ceiling-fan',
    description: 'Silent operation aerodynamic blades',
    long_description: 'Silent operation aerodynamic blades. Authentic Havells product.',
    price: 85.00,
    category: 'Smart Home',
    brand: 'Havells',
    image_url: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop',
    stock: 45,
    specifications: { 'Brand': 'Havells', 'Category': 'Smart Home' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-114',
    name: 'Luker 15W LED Panel',
    slug: 'luker-15w-led-panel',
    description: 'Recessed LED downlight',
    long_description: 'Recessed LED downlight. Authentic Luker product.',
    price: 12.00,
    category: 'Smart Home',
    brand: 'Luker',
    image_url: 'https://images.unsplash.com/photo-1565538420870-da08ff96a207?w=800&auto=format&fit=crop',
    stock: 200,
    specifications: { 'Brand': 'Luker', 'Category': 'Smart Home' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-115',
    name: 'Yale YDD424 Smart Door Lock',
    slug: 'yale-ydd424-smart-door-lock',
    description: 'Biometric and PIN smart lock',
    long_description: 'Biometric and PIN smart lock. Authentic Yale product.',
    price: 250.00,
    category: 'Smart Home',
    brand: 'Yale',
    image_url: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800&auto=format&fit=crop',
    stock: 20,
    specifications: { 'Brand': 'Yale', 'Category': 'Smart Home' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Hometheatre
  {
    id: 'prd-116',
    name: 'LG CineBeam 4K Projector',
    slug: 'lg-cinebeam-4k-projector',
    description: 'Laser 4K UHD smart projector',
    long_description: 'Laser 4K UHD smart projector. Authentic LG product.',
    price: 1499.00,
    category: 'Home Theatre & Audio',
    brand: 'LG',
    image_url: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=800&auto=format&fit=crop',
    stock: 12,
    specifications: { 'Brand': 'LG', 'Category': 'Home Theatre & Audio' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-117',
    name: 'Epson Home Cinema 3800',
    slug: 'epson-home-cinema-3800',
    description: '4K PRO-UHD projector',
    long_description: '4K PRO-UHD projector. Authentic Epson product.',
    price: 1299.00,
    category: 'Home Theatre & Audio',
    brand: 'Epson',
    image_url: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=800&auto=format&fit=crop',
    stock: 15,
    specifications: { 'Brand': 'Epson', 'Category': 'Home Theatre & Audio' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-118',
    name: 'Sony VPL-VW290ES Projector',
    slug: 'sony-vpl-vw290es-projector',
    description: 'Native 4K SXRD projector',
    long_description: 'Native 4K SXRD projector. Authentic Sony product.',
    price: 3999.00,
    category: 'Home Theatre & Audio',
    brand: 'Sony',
    image_url: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=800&auto=format&fit=crop',
    stock: 5,
    specifications: { 'Brand': 'Sony', 'Category': 'Home Theatre & Audio' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-119',
    name: 'Yamaha RX-V6A AV Receiver',
    slug: 'yamaha-rx-v6a-av-receiver',
    description: '7.2 ch 8K AV receiver',
    long_description: '7.2 ch 8K AV receiver. Authentic Yamaha product.',
    price: 649.00,
    category: 'Home Theatre & Audio',
    brand: 'Yamaha',
    image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop',
    stock: 18,
    specifications: { 'Brand': 'Yamaha', 'Category': 'Home Theatre & Audio' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-120',
    name: 'Marantz Cinema 50',
    slug: 'marantz-cinema-50',
    description: 'Premium 9.4 ch AV receiver',
    long_description: 'Premium 9.4 ch AV receiver. Authentic Marantz product.',
    price: 1200.00,
    category: 'Home Theatre & Audio',
    brand: 'Marantz',
    image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop',
    stock: 10,
    specifications: { 'Brand': 'Marantz', 'Category': 'Home Theatre & Audio' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-121',
    name: 'Tone Winner AT-300 Processor',
    slug: 'tone-winner-at-300-processor',
    description: '16 channel AV processor',
    long_description: '16 channel AV processor. Authentic Tone Winner product.',
    price: 950.00,
    category: 'Home Theatre & Audio',
    brand: 'Tone Winner',
    image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop',
    stock: 8,
    specifications: { 'Brand': 'Tone Winner', 'Category': 'Home Theatre & Audio' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-122',
    name: 'Paradigm Premier 800F',
    slug: 'paradigm-premier-800f',
    description: 'Floorstanding loudspeaker',
    long_description: 'Floorstanding loudspeaker. Authentic Paradigm product.',
    price: 1099.00,
    category: 'Home Theatre & Audio',
    brand: 'Paradigm',
    image_url: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&auto=format&fit=crop',
    stock: 14,
    specifications: { 'Brand': 'Paradigm', 'Category': 'Home Theatre & Audio' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-123',
    name: 'Klipsch RP-8000F',
    slug: 'klipsch-rp-8000f',
    description: 'Reference premiere floorstanding speaker',
    long_description: 'Reference premiere floorstanding speaker. Authentic Klipsch product.',
    price: 899.00,
    category: 'Home Theatre & Audio',
    brand: 'Klipsch',
    image_url: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&auto=format&fit=crop',
    stock: 22,
    specifications: { 'Brand': 'Klipsch', 'Category': 'Home Theatre & Audio' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-124',
    name: 'OSD Black Series In-Ceiling',
    slug: 'osd-black-series-in-ceiling',
    description: '8-inch Atmos architectural speaker',
    long_description: '8-inch Atmos architectural speaker. Authentic OSD Audio product.',
    price: 120.00,
    category: 'Home Theatre & Audio',
    brand: 'OSD Audio',
    image_url: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=800&auto=format&fit=crop',
    stock: 45,
    specifications: { 'Brand': 'OSD Audio', 'Category': 'Home Theatre & Audio' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-125',
    name: 'Tone Winner AD-7300PA+ Amp',
    slug: 'tone-winner-ad-7300pa-amp',
    description: '7 channel power amplifier',
    long_description: '7 channel power amplifier. Authentic Tone Winner product.',
    price: 1100.00,
    category: 'Home Theatre & Audio',
    brand: 'Tone Winner',
    image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop',
    stock: 6,
    specifications: { 'Brand': 'Tone Winner', 'Category': 'Home Theatre & Audio' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-126',
    name: 'Liberty 120" Motorized Screen',
    slug: 'liberty-120-motorized-screen',
    description: 'ALR projector screen',
    long_description: 'ALR projector screen. Authentic Liberty product.',
    price: 450.00,
    category: 'Home Theatre & Audio',
    brand: 'Liberty',
    image_url: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=800&auto=format&fit=crop',
    stock: 12,
    specifications: { 'Brand': 'Liberty', 'Category': 'Home Theatre & Audio' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // MCB and DB
  {
    id: 'prd-127',
    name: 'IndoAsian Optipro 16A MCB',
    slug: 'indoasian-optipro-16a-mcb',
    description: 'Single pole C-curve MCB',
    long_description: 'Single pole C-curve MCB. Authentic IndoAsian product.',
    price: 4.50,
    category: 'MCB & DB',
    brand: 'IndoAsian',
    image_url: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=800&auto=format&fit=crop',
    stock: 120,
    specifications: { 'Brand': 'IndoAsian', 'Category': 'MCB & DB' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-128',
    name: 'Hager Novello 32A DP MCB',
    slug: 'hager-novello-32a-dp-mcb',
    description: 'Double pole circuit breaker',
    long_description: 'Double pole circuit breaker. Authentic Hager product.',
    price: 12.50,
    category: 'MCB & DB',
    brand: 'Hager',
    image_url: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=800&auto=format&fit=crop',
    stock: 80,
    specifications: { 'Brand': 'Hager', 'Category': 'MCB & DB' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prd-129',
    name: 'Legrand 8-Way DB',
    slug: 'legrand-8-way-db',
    description: 'SPN Distribution Board',
    long_description: 'SPN Distribution Board. Authentic Legrand product.',
    price: 45.00,
    category: 'MCB & DB',
    brand: 'Legrand',
    image_url: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=800&auto=format&fit=crop',
    stock: 35,
    specifications: { 'Brand': 'Legrand', 'Category': 'MCB & DB' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  }
];

export const HOME_THEATRE_PRODUCTS = SAMPLE_PRODUCTS.filter(
  (p) => p.category === 'Home Theatre & Audio'
);
