import type { Product } from '@/types';

export const SAMPLE_PRODUCTS: Product[] = [
  // ── Switches & Sockets ──────────────────────────────────────────────────
  {
    id: 'sw-001',
    name: 'Legrand Modular 3-Pin Socket',
    slug: 'legrand-modular-3pin-socket',
    description: '3-pin, 16A rated, brass terminals, white finish',
    long_description: 'Standard modular socket with brass terminals for maximum conductivity. Complies with IS 1293:2019. Fits standard modular plates.',
    price: 8.99,
    category: 'Switches & Sockets',
    brand: 'Legrand',
    image_url: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=800&auto=format&fit=crop',
    stock: 240,
    specifications: {
      'Type': '3-pin socket',
      'Rating': '16A @ 250V',
      'Terminal': 'Brass screw',
      'Standard': 'IS 1293:2019',
      'Installation': 'Modular plate',
      'Finish': 'Glossy white',
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sw-002',
    name: 'Schneider 6A Light Switch 2-Way',
    slug: 'schneider-6a-light-switch-2way',
    description: '2-way rocker switch, 6A, polished steel plate',
    long_description: 'Premium 2-way switch with polished stainless steel finish. Soft-touch rocker mechanism rated for 100,000 operations.',
    price: 12.50,
    category: 'Switches & Sockets',
    brand: 'Schneider',
    image_url: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=800&auto=format&fit=crop',
    stock: 180,
    specifications: {
      'Type': '2-way rocker',
      'Rating': '6A @ 250V',
      'Plate': 'Stainless steel',
      'Mechanism': '100k operations',
      'Gang': 'Single',
      'Finish': 'Brushed',
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sw-003',
    name: 'Roma USB Charging Socket 2.4A',
    slug: 'roma-usb-charging-socket',
    description: 'Dual USB-A + 3-pin socket combo, 2.4A charging',
    long_description: 'Combination socket with integrated USB charging ports. Delivers 2.4A shared across two USB-A ports. Independent 16A socket for appliances.',
    price: 18.99,
    category: 'Switches & Sockets',
    brand: 'Roma',
    image_url: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=800&auto=format&fit=crop',
    stock: 95,
    specifications: {
      'USB Output': '5V 2.4A (shared)',
      'Socket Rating': '16A @ 250V',
      'Ports': '2× USB-A',
      'Type': 'Combo unit',
      'Standard': 'IS 1293',
      'Installation': 'Modular',
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // ── Cables & Wires ───────────────────────────────────────────────────────
  {
    id: 'cb-001',
    name: 'Finolex 2.5mm² House Wire 90m',
    slug: 'finolex-house-wire-2-5mm-90m',
    description: 'FR PVC insulated copper wire, 2.5mm², red, 90m coil',
    long_description: 'Flame-retardant house wiring cable. Pure copper conductor rated for 25A continuous. Meets IS 694:2010 standard.',
    price: 42.00,
    category: 'Cables & Wires',
    brand: 'Finolex',
    image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&auto=format&fit=crop',
    stock: 65,
    specifications: {
      'Conductor': '2.5mm² copper',
      'Insulation': 'FR PVC',
      'Current': '25A continuous',
      'Length': '90 meters',
      'Color': 'Red',
      'Standard': 'IS 694:2010',
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cb-002',
    name: 'Belkin CAT6 Ethernet 10m',
    slug: 'belkin-cat6-ethernet-10m',
    description: 'Gigabit Ethernet, 23AWG, snagless RJ45, blue',
    long_description: 'CAT6 patch cable with gold-plated connectors and snagless boots. Supports 10Gbps at shorter distances, 1Gbps at full length.',
    price: 15.99,
    category: 'Cables & Wires',
    brand: 'Belkin',
    image_url: 'https://images.unsplash.com/photo-1606904825846-647eb07f5be2?w=800&auto=format&fit=crop',
    stock: 140,
    specifications: {
      'Standard': 'CAT6 TIA/EIA 568',
      'Speed': '1Gbps @ 100m',
      'Conductor': '23AWG copper',
      'Connector': 'RJ45 snagless',
      'Length': '10 meters',
      'Color': 'Blue',
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cb-003',
    name: 'AudioQuest Evergreen RCA 2m',
    slug: 'audioquest-evergreen-rca',
    description: 'Solid long-grain copper interconnect, RCA to RCA',
    long_description: 'High-purity copper conductors with asymmetrical double-balanced geometry. Cold-welded gold-plated plugs minimize distortion.',
    price: 32.00,
    category: 'Cables & Wires',
    brand: 'AudioQuest',
    image_url: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800&auto=format&fit=crop',
    stock: 48,
    specifications: {
      'Conductor': 'LGC copper',
      'Geometry': 'Double-balanced',
      'Connector': 'Gold-plated RCA',
      'Length': '2 meters',
      'Shielding': 'Foil + braid',
      'Use': 'Analog audio',
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cb-004',
    name: 'Cable Matters HDMI 2.1 8K 3m',
    slug: 'cable-matters-hdmi-2-1-3m',
    description: '48Gbps bandwidth, 8K@60Hz, 4K@120Hz, HDR, eARC',
    long_description: 'Ultra-high-speed HDMI 2.1 cable. Full 48Gbps bandwidth for 8K and 4K@120Hz gaming. Supports eARC for lossless audio passthrough to soundbars.',
    price: 22.99,
    category: 'Cables & Wires',
    brand: 'Cable Matters',
    image_url: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=800&auto=format&fit=crop',
    stock: 88,
    specifications: {
      'Standard': 'HDMI 2.1',
      'Bandwidth': '48 Gbps',
      'Video': '8K@60Hz / 4K@120Hz',
      'Audio': 'eARC passthrough',
      'Length': '3 meters',
      'HDR': 'HDR10, Dolby Vision',
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // ── Home Theatre & Audio ─────────────────────────────────────────────────
  {
    id: 'ht-001',
    name: 'Yamaha RX-V6A 7.2-Ch AVR',
    slug: 'yamaha-rx-v6a-avr',
    description: '7.2-channel receiver, 100W/ch, HDMI 2.1, 8K passthrough',
    long_description: 'Network AV receiver with MusicCast multi-room, voice control integration, and immersive Dolby Atmos / DTS:X surround. 7 HDMI in, 2 out with eARC support.',
    price: 649.99,
    category: 'Home Theatre & Audio',
    brand: 'Yamaha',
    image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop',
    stock: 12,
    specifications: {
      'Channels': '7.2',
      'Power': '100W/ch @ 8Ω',
      'HDMI': '7 in / 2 out (2.1)',
      'Video': '8K60 / 4K120',
      'Formats': 'Atmos, DTS:X',
      'Network': 'WiFi, BT, AirPlay 2',
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ht-002',
    name: 'Klipsch R-625FA Floorstanding',
    slug: 'klipsch-r625fa-floorstanding',
    description: 'Dolby Atmos floorstanding, dual 6.5" woofers, 400W peak',
    long_description: 'Integrated elevation channel for immersive Atmos playback. Horn-loaded tweeter, spun-copper woofers. Compatible with any Dolby Atmos AVR.',
    price: 549.00,
    category: 'Home Theatre & Audio',
    brand: 'Klipsch',
    image_url: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&auto=format&fit=crop',
    stock: 8,
    specifications: {
      'Type': 'Floorstanding',
      'Drivers': '1" + 2× 6.5" + 5.25"',
      'Frequency': '38Hz–21kHz ±3dB',
      'Sensitivity': '97dB @ 2.83V/1m',
      'Power': '400W peak',
      'Impedance': '8Ω',
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ht-003',
    name: 'Sonos Arc SL Soundbar',
    slug: 'sonos-arc-sl-soundbar',
    description: 'Dolby Atmos soundbar, 11 drivers, WiFi streaming',
    long_description: 'Premium soundbar with upward-firing drivers for spatial audio. Supports Dolby Atmos, AirPlay 2, and Sonos multi-room. No microphones for privacy.',
    price: 879.00,
    category: 'Home Theatre & Audio',
    brand: 'Sonos',
    image_url: 'https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=800&auto=format&fit=crop',
    stock: 15,
    specifications: {
      'Drivers': '11 (8 woofer, 3 tweet)',
      'Channels': '5.0.2 virtual',
      'Formats': 'Dolby Atmos',
      'Connectivity': 'HDMI eARC, WiFi',
      'Streaming': 'AirPlay 2, Spotify',
      'Dimensions': '1141 × 87 × 116mm',
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ht-004',
    name: 'Epson EH-TW7100 Projector',
    slug: 'epson-eh-tw7100-projector',
    description: '4K PRO-UHD, 3000 lumens, HDR10, 3LCD, lens shift',
    long_description: 'Home cinema projector with 4K enhancement, wide color gamut, and motorized lens controls. Frame interpolation up to 120Hz for smooth motion.',
    price: 1899.00,
    category: 'Home Theatre & Audio',
    brand: 'Epson',
    image_url: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=800&auto=format&fit=crop',
    stock: 5,
    specifications: {
      'Resolution': '4K PRO-UHD (1920×1080×2)',
      'Brightness': '3000 ANSI lumens',
      'Contrast': '200,000:1 dynamic',
      'HDR': 'HDR10, HLG',
      'Throw': '1.35–2.84:1 motorized',
      'Lamp': '7500h eco mode',
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ht-005',
    name: 'Denon AVR-S970H 7.2-Ch Receiver',
    slug: 'denon-avr-s970h',
    description: '7.2-ch, 90W/ch, HDMI 2.1, Audyssey MultEQ XT',
    long_description: 'Mid-range receiver with full HDMI 2.1, Audyssey room correction, HEOS multi-room streaming, and 8K/4K120 passthrough.',
    price: 479.00,
    category: 'Home Theatre & Audio',
    brand: 'Denon',
    image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop&q=80&w=800',
    stock: 18,
    specifications: {
      'Channels': '7.2',
      'Power': '90W/ch @ 8Ω',
      'HDMI': '6 in / 2 out (2.1)',
      'Video': '8K60 / 4K120',
      'Room EQ': 'Audyssey MultEQ XT',
      'Network': 'HEOS, AirPlay 2, BT',
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ht-006',
    name: 'SVS SB-1000 Pro Subwoofer',
    slug: 'svs-sb1000-pro-subwoofer',
    description: '12" sealed sub, 325W RMS DSP amp, app control',
    long_description: 'Compact sealed subwoofer with Sledge DSP amplifier. App control for EQ, volume, and custom presets. Delivers tight, accurate bass to 20Hz.',
    price: 599.00,
    category: 'Home Theatre & Audio',
    brand: 'SVS',
    image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&auto=format&fit=crop&q=80',
    stock: 9,
    specifications: {
      'Driver': '12" high-excursion',
      'Amplifier': '325W RMS DSP',
      'Frequency': '20–270Hz ±3dB',
      'Type': 'Sealed enclosure',
      'App': 'iOS + Android EQ',
      'Dimensions': '13" cube',
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // ── Smart Home ───────────────────────────────────────────────────────────
  {
    id: 'sh-001',
    name: 'Sonoff WiFi Smart Switch',
    slug: 'sonoff-wifi-smart-switch',
    description: 'WiFi relay module, 10A, app control, Alexa compatible',
    long_description: 'Wireless smart switch for retrofit installations. Controls lights and appliances via smartphone app. Works with Alexa, Google Assistant, and IFTTT.',
    price: 14.99,
    category: 'Smart Home',
    brand: 'Sonoff',
    image_url: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop',
    stock: 210,
    specifications: {
      'Rating': '10A @ 250V AC',
      'Connectivity': 'WiFi 2.4GHz',
      'Protocol': '802.11 b/g/n',
      'Voice': 'Alexa, Google',
      'App': 'eWeLink (iOS/Android)',
      'Dimensions': '86 × 86 × 25mm',
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sh-002',
    name: 'Aqara Door Sensor Zigbee',
    slug: 'aqara-door-sensor-zigbee',
    description: 'Zigbee 3.0, magnetic contact, 2-year battery',
    long_description: 'Ultra-compact wireless door/window sensor. Triggers automations when opened or closed. Requires compatible Zigbee hub.',
    price: 19.99,
    category: 'Smart Home',
    brand: 'Aqara',
    image_url: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800&auto=format&fit=crop',
    stock: 155,
    specifications: {
      'Protocol': 'Zigbee 3.0',
      'Type': 'Magnetic contact',
      'Battery': 'CR1632 (2 years)',
      'Range': '10m open field',
      'Hub': 'Requires Zigbee hub',
      'Dimensions': '36 × 12 × 7mm',
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sh-003',
    name: 'Philips Hue White A60 E27',
    slug: 'philips-hue-white-a60-e27',
    description: 'Smart LED bulb, 9W (60W equiv), dimmable, Bluetooth + Zigbee',
    long_description: 'Tunable white smart bulb with wireless dimming and scheduling. Direct Bluetooth control via app, or connect to Hue Bridge for full automation.',
    price: 16.50,
    category: 'Smart Home',
    brand: 'Philips',
    image_url: 'https://images.unsplash.com/photo-1565538420870-da08ff96a207?w=800&auto=format&fit=crop',
    stock: 185,
    specifications: {
      'Power': '9W (60W equiv)',
      'Lumens': '806 lm',
      'Color Temp': '2700K warm white',
      'Protocol': 'Bluetooth + Zigbee',
      'Fitting': 'E27 screw',
      'Lifespan': '25,000 hours',
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // ── Deals ────────────────────────────────────────────────────────────────
  {
    id: 'deal-001',
    name: 'Switch Socket Combo Pack (4+4)',
    slug: 'switch-socket-combo-pack',
    description: '4× 6A switches + 4× 16A sockets, modular white',
    long_description: 'Starter pack for a single room installation. Includes four 1-way switches and four 3-pin sockets. All units modular-compatible with standard plates.',
    price: 58.00,
    category: 'Deals',
    brand: 'Legrand',
    image_url: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=800&auto=format&fit=crop',
    stock: 42,
    specifications: {
      'Bundle': '4× switch + 4× socket',
      'Switch Rating': '6A @ 250V',
      'Socket Rating': '16A @ 250V',
      'Type': 'Modular',
      'Finish': 'White',
      'Savings': '25% vs individual',
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'deal-002',
    name: 'Home Theatre Starter Kit',
    slug: 'home-theatre-starter-kit',
    description: '5.1 speaker set + cables + wall mounts (no AVR)',
    long_description: 'Complete passive speaker package: 5× satellite speakers, 1× powered subwoofer, speaker wire, HDMI cable, and adjustable wall mounts. Pair with any AVR.',
    price: 389.00,
    category: 'Deals',
    brand: 'Polk Audio',
    image_url: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=800&auto=format&fit=crop',
    stock: 18,
    specifications: {
      'Bundle': '5 sat + 1 sub + cables',
      'Speakers': 'Polk T15 bookshelf',
      'Subwoofer': '10" 100W powered',
      'Cables': 'HDMI + 16AWG speaker',
      'Mounts': 'Tilt/swivel × 5',
      'Savings': '30% vs individual',
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'deal-003',
    name: 'Smart Home Essentials Bundle',
    slug: 'smart-home-essentials-bundle',
    description: 'Hub + 4× WiFi switches + 2× door sensors',
    long_description: 'Everything to automate one apartment: Zigbee hub, four smart switches, two door/window sensors. Pre-configured scenes included.',
    price: 149.00,
    category: 'Deals',
    brand: 'Aqara',
    image_url: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80',
    stock: 28,
    specifications: {
      'Bundle': 'Hub + 4 switch + 2 sensor',
      'Hub': 'Zigbee 3.0 + WiFi',
      'Switches': '10A relay modules',
      'Sensors': 'Magnetic contact',
      'App': 'iOS + Android',
      'Savings': '35% vs individual',
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const HOME_THEATRE_PRODUCTS = SAMPLE_PRODUCTS.filter(
  (p) => p.category === 'Home Theatre & Audio'
);
